/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
(function(a,i){var k,o,h=function(){},d=function(a){for(var c in a)return 0;return 1},m={}.toString,g=function(a){return m.call(a)=="[object Function]"},n=function(a){return m.call(a)=="[object String]"},b=function(a){return m.call(a)=="[object Array]"},f=function(a,c){if(a)for(var b=0;b<a.length;)c(a[b++])},l=function(a,c){for(var b in c)a[b]=c[b];return a},q=function(a,c){return l(Error(a),{src:"dojoLoader",info:c})},r=1,c=function(){return"_"+r++},e=function(a,c,b){return Ca(a,c,b,0,e)},j=this,
p=j.document,t=p&&p.createElement("DiV"),u=e.has=function(a){return s[a]=g(s[a])?s[a](j,p,t):s[a]},s=u.cache=i.hasCache;u.add=function(a,c,b,e){(s[a]===void 0||e)&&(s[a]=c);return b&&u(a)};for(var B in a.has)u.add(B,a.has[B],0,1);var w=0,C=[],J=0,D=h,S=h,Q;e.isXdUrl=h;e.initSyncLoader=function(a,c,b){J||(J=a,D=c,S=b);return{sync:"sync",xd:"xd",arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:C,modules:L,execQ:M,getModule:T,injectModule:ga,setArrived:W,signal:H,finishExec:Z,execModule:$,
dojoRequirePlugin:J,getLegacyMode:function(){return w},holdIdle:function(){R++},releaseIdle:function(){aa()}}};var ba=location.protocol,v=location.host,z=!v;e.isXdUrl=function(a){if(z||/^\./.test(a))return!1;if(/^\/\//.test(a))return!0;return(a=a.match(/^([^\/\:]+\:)\/\/([^\/]+)/))&&(a[1]!=ba||a[2]!=v)};u.add("dojo-force-activex-xhr",!p.addEventListener&&window.location.protocol=="file:");u.add("native-xhr",typeof XMLHttpRequest!="undefined");if(u("native-xhr")&&!u("dojo-force-activex-xhr"))Q=function(){return new XMLHttpRequest};
else{B=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"];var E;for(k=0;k<3;)try{if(E=B[k++],new ActiveXObject(E))break}catch(A){}Q=function(){return new ActiveXObject(E)}}e.getXhr=Q;u.add("dojo-gettext-api",1);e.getText=function(a,c,b){var e=Q();e.open("GET",ha(a),!1);e.send(null);if(e.status==200||!location.host&&!e.status)b&&b(e.responseText,c);else throw q("xhrFailed",e.status);return e.responseText};var F=new Function("__text","return eval(__text);");e.eval=function(a,c){return F(a+
"\r\n////@ sourceURL="+c)};var K={},H=e.signal=function(a,c){var e=K[a];f(e&&e.slice(0),function(a){a.apply(null,b(c)?c:[c])})},U=e.on=function(a,c){var b=K[a]||(K[a]=[]);b.push(c);return{remove:function(){for(var a=0;a<b.length;a++)if(b[a]===c){b.splice(a,1);break}}}},V=[],I={},y=[],O={},x={},G=[],L={},sa="",ca={},da={};B={};var ja=function(a){for(var c in da){var b=c.match(/^url\:(.+)/);b?ca[Da(b[1],a)]=da[c]:c!="*noref"&&(ca[ia(c,a).mid]=da[c])}da={}},ta=function(a,c,b){c.splice(0,c.length);var e,
j=0;for(e in a)c.push([e,a[e]]),a[e]==b&&(j=e);c.sort(function(a,c){return c[0].length-a[0].length});for(a=0;a<c.length;)b=c[a++],b[2]=RegExp("^"+b[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"(/|$)"),b[3]=b[0].length+1;return j},Ea=function(a,c){var b=a.name;b||(b=a,a={name:b});a=l({main:"main",mapProg:[]},a);a.location=(c||"")+(a.location?a.location:b);a.reverseName=ta(a.packageMap,a.mapProg,b);if(!a.main.indexOf("./"))a.main=a.main.substring(2);l(I,a.paths);O[b]=a;x[b]=
b},ka=function(a,c){for(var b in a){if(b=="waitSeconds")e.waitms=(a[b]||0)*1E3;b=="cacheBust"&&(sa=a[b]?n(a[b])?a[b]:(new Date).getTime()+"":"");if(b=="baseUrl"||b=="combo")e[b]=a[b];if(b=="async"){var j=a[b];e.legacyMode=w=n(j)&&/sync|legacyAsync/.test(j)?j:!j?"sync":!1;e.async=!w}a[b]!==s&&(e.rawConfig[b]=a[b],b!="has"&&u.add("config-"+b,a[b],0,c))}if(!e.baseUrl)e.baseUrl="./";/\/$/.test(e.baseUrl)||(e.baseUrl+="/");for(b in a.has)u.add(b,a.has[b],0,c);f(a.packages,Ea);for(o in a.packagePaths)f(a.packagePaths[o],
function(a){Ea(a,o+"/")});ta(l(I,a.paths),y);f(a.aliases,function(a){n(a[0])&&(a[0]=RegExp("^"+a[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"$"));V.push(a)});ta(l(x,a.packageMap),G);if(a.cache)ja(),da=a.cache,a.cache["*noref"]&&ja();H("config",[a,e.rawConfig])},P,ua,la=p.getElementsByTagName("script");for(k=0;k<la.length&&!ua;k++)if((P=la[k].getAttribute("src"))&&(ua=P.match(/(.*)\/?dojo\.js(\W|$)/i)))a.baseUrl=a.baseUrl||i.baseUrl||ua[1],(P=la[k].getAttribute("data-dojo-config")||
la[k].getAttribute("djConfig"))&&(B=e.eval("({ "+P+" })","data-dojo-config"));e.rawConfig={};ka(i,1);ka(a,1);ka(B,1);var ea=function(a){R++;f(a.deps,ga);aa()},Ca=function(a,j,f,d,g){if(n(a)){if((j=T(a,d,!0))&&j.executed)return j.result;throw q("undefinedModule",a);}b(a)||(ka(a),a=j,j=f);if(b(a)){for(var f="require*"+c(),p,t=[],m=0;m<a.length;){p=a[m++];if(p in{exports:1,module:1})throw q("illegalModuleId",p);t.push(T(p,d))}j=l(ma("",f,0,""),{injected:2,deps:t,def:j||h,require:d?d.require:e});L[j.mid]=
j;ea(j);a=R&&e.async;R++;$(j,a);aa();j.executed||M.push(j);X()}return g},Fa=function(a){if(!a)return e;var c=a.require;if(!c)c=function(b,e,j){return Ca(b,e,j,a,c)},a.require=l(c,e),c.module=a,c.toUrl=function(c){return Da(c,a)},c.toAbsMid=function(c){return va(c,a)};return c},M=[],na=[],N={},Ga=function(a){a.injected=1;N[a.mid]=1;a.url&&(N[a.url]=a.pack||1)},W=function(a){a.injected=2;delete N[a.mid];a.url&&delete N[a.url];d(N)&&(oa(),w=="xd"&&(w="sync"))},Ra=e.idle=function(){return!na.length&&
d(N)&&!M.length&&!R},wa=function(a,c){for(var b=0;b<c.length;b++)if(c[b][2].test(a))return c[b];return 0},Ha=function(a){for(var c=[],b,e,a=a.replace(/\\/g,"/").split("/");a.length;)b=a.shift(),b==".."&&c.length&&e!=".."?(c.pop(),e=c[c.length-1]):b!="."&&c.push(e=b);return c.join("/")},ma=function(a,c,b,j,f){var d=e.isXdUrl(j);return{pid:a,mid:c,pack:b,url:j,executed:0,def:0,isXd:d,isAmd:!!(d||O[a]&&O[a].isAmd),cacheId:f}},Ia=function(a,c,b,e,j,d,l,p){var h,n,t,m=0;t=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||
t&&!c)return ma(0,a,0,a);else{a=Ha(t?c.mid+"/../"+a:a);if(/^\./.test(a))throw q("irrationalPath",a);if(t=(c=c&&c.pack&&c.pack.mapProg)&&wa(a,c)||wa(a,d)){c=t[1];a=a.substring(t[3]);h=b[c];if(!a)a=h.main;n=a;m=h.reverseName+"/"+a;a=c+"/"+a}else c="";var r=0;f(V,function(c){var b=a.match(c[0]);b&&b.length>0&&(r=g(c[1])?a.replace(c[0],c[1]):c[1])});if(r)return Ia(r,0,b,e,j,d,l,p);if(b=e[a])return p?ma(b.pid,b.mid,b.pack,b.url,m):e[a]}e=(t=wa(a,l))?t[1]+a.substring(t[3]-1):c?h.location+"/"+n:u("config-tlmSiblingOfDojo")?
"../"+a:a;/(^\/)|(\:)/.test(e)||(e=j+e);e+=".js";return ma(c,a,h,Ha(e),m)},ia=function(a,c){return Ia(a,c,O,L,e.baseUrl,G,y)},Ja=function(a,c,b){return a.normalize?a.normalize(c,function(a){return va(a,b)}):va(c,b)},Ka=0,T=function(a,c,b){var e,j;(e=a.match(/^(.+?)\!(.*)$/))?(j=T(e[1],c,b),w=="sync"&&!j.executed&&(ga(j),j.injected===2&&!j.executed&&(R++,$(j),aa()),j.executed?pa(j):M.unshift(j)),j.executed===5&&!j.load&&pa(j),j.load?(e=Ja(j,e[2],c),a=j.mid+"!"+(j.dynamic?++Ka+"!":"")+e):(e=e[2],a=
j.mid+"!"+ ++Ka+"!waitingForPlugin"),a={plugin:j,mid:a,req:Fa(c),prid:e}):a=ia(a,c);return L[a.mid]||!b&&(L[a.mid]=a)},va=e.toAbsMid=function(a,c){return ia(a,c).mid},Da=e.toUrl=function(a,c){var b=a.match(/(.+)(\.[^\/\.]+?)$/),e=b&&b[2]||"",b=ia(b&&b[1]||a,c),j=b.url,j=typeof b.pid=="string"?j.substring(0,j.length-3):j;return ha(j+e)},La={injected:2,executed:5,def:3,result:3};P=function(a){return L[a]=l({mid:a},La)};var Sa=P("require"),Ta=P("exports"),Ua=P("module"),qa={},xa=0,pa=function(a){var c=
a.result;a.dynamic=c.dynamic;a.normalize=c.normalize;a.load=c.load;return a},Va=function(a){var c={};f(a.loadQ,function(b){var e=Ja(a,b.prid,b.req.module),j=a.dynamic?b.mid.replace(/waitingForPlugin$/,e):a.mid+"!"+e,e=l(l({},b),{mid:j,prid:e,injected:0});L[j]||Ma(L[j]=e);c[b.mid]=L[j];W(b);delete L[b.mid]});a.loadQ=0;var b=function(a){for(var b=a.deps||[],e=0;e<b.length;e++)(a=c[b[e].mid])&&(b[e]=a)},e;for(e in L)b(L[e]);f(M,b)},Z=function(a){e.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=
xa++;f(a.provides,function(a){a()});a.loadQ&&(pa(a),Va(a));for(k=0;k<M.length;)M[k]===a?M.splice(k,1):k++},Wa=[],$=function(a,c){if(a.executed===4)return e.trace("loader-circular-dependency",[Wa.concat(b).join("->")]),!a.def||c?qa:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return qa;var b=a.mid,j=a.deps||[],f,d=[],l=0;for(a.executed=4;l<j.length;){f=j[l++];f=f===Sa?Fa(a):f===Ta?a.cjs.exports:f===Ua?a.cjs:$(f,c);if(f===qa)return a.executed=0,e.trace("loader-exec-module",["abort",b]),qa;d.push(f)}e.trace("loader-run-factory",
[a.mid]);var b=a.def,p;C.unshift(a);if(u("config-dojo-loader-catches"))try{p=g(b)?b.apply(null,d):b}catch(h){H("error",a.result=q("factoryThrew",[a,h]))}else p=g(b)?b.apply(null,d):b;a.result=p===void 0&&a.cjs?a.cjs.exports:p;C.shift(a);Z(a)}return a.result},R=0,X=function(){if(!R){R++;D();for(var a,c,b=0;b<M.length;)a=xa,c=M[b],$(c),a!=xa?(D(),b=0):b++;aa()}},aa=function(){R--;Ra()&&H("idle",[])},ha=function(a){a+="";return a+(sa?(/\?/.test(a)?"&":"?")+sa:"")},Ma=function(a){var c=a.plugin;c.executed===
5&&!c.load&&pa(c);var b=function(c){a.result=c;W(a);Z(a);X()};Ga(a);c.load?c.load(a.prid,a.req,b):c.loadQ?c.loadQ.push(a):(M.unshift(c),ga(c),c.load?c.load(a.prid,a.req,b):c.loadQ=[a])},Y=0,fa=0,ya=0,za=function(a,c){ya=1;if(u("config-dojo-loader-catches"))try{a===Y?Y.call(null):e.eval(a,c.mid)}catch(b){H("error",q("evalModuleThrew",c))}else a===Y?Y.call(null):e.eval(a,c.mid);ya=0},ga=function(a){var c=a.mid,b=a.url;if(!a.executed&&!a.injected&&!(N[c]||a.url&&(a.pack&&N[a.url]===a.pack||N[a.url]==
1)))if(a.plugin)Ma(a);else{Ga(a);var j=function(){Na(a);a.injected!==2&&(W(a),l(a,La));w?!C.length&&X():X()};if(Y=ca[c]||ca[a.cacheId])e.trace("loader-inject",["cache",a.mid,b]),za(Y,a),j();else{if(w)if(a.isXd)w=="sync"&&(w="xd");else if(!(a.isAmd&&w!="sync")){var d=function(d){if(w=="sync"){C.unshift(a);za(d,a);C.shift();Na(a);a.cjs||(W(a),Z(a));if(a.finish){var d=c+"*finish",l=a.finish;delete a.finish;Aa(d,["dojo",("dojo/require!"+l.join(",")).replace(/\./g,"/")],function(a){f(l,function(c){a.require(c)})});
M.unshift(T(d))}j()}else(d=S(a,d))?(za(d,a),j()):(fa=a,e.injectUrl(ha(b),j,a),fa=0)};e.trace("loader-inject",["xhr",a.mid,b,w!="sync"]);if(u("config-dojo-loader-catches"))try{e.getText(b,w!="sync",d)}catch(g){H("error",q("xhrInjectFailed",[a,g]))}else e.getText(b,w!="sync",d);return}e.trace("loader-inject",["script",a.mid,b]);fa=a;e.injectUrl(ha(b),j,a);fa=0}}},Ba=function(a,c,b){e.trace("loader-define-module",[a.mid,c]);var j=a.mid;if(a.injected===2)return H("error",q("multipleDefine",a)),a;l(a,
{deps:c,def:b,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(c){a.cjs.exports=c}}});for(var f=0;f<c.length;f++)c[f]=T(c[f],a);w&&!N[j]&&(ea(a),M.push(a),X());W(a);if(!g(b)&&!c.length)a.result=b,Z(a);return a},Na=function(a,c){ja(a);for(var b=[],e,j;na.length;)j=na.shift(),c&&(j[0]=c.shift()),e=j[0]&&T(j[0])||a,b.push(Ba(e,j[1],j[2]));f(b,ea)},ra=0,oa=h,Oa=h,oa=function(){ra&&clearTimeout(ra);ra=0},Oa=function(){oa();e.waitms&&(ra=setTimeout(function(){oa();H("error",q("timeout",N))},
e.waitms))};u.add("ie-event-behavior",p.attachEvent&&(typeof opera==="undefined"||opera.toString()!="[object Opera]"));var Pa=function(a,c,b,e){return u("ie-event-behavior")?(a.attachEvent(b,e),function(){a.detachEvent(b,e)}):(a.addEventListener(c,e,!1),function(){a.removeEventListener(c,e,!1)})},Xa=Pa(window,"load","onload",function(){e.pageLoaded=1;p.readyState!="complete"&&(p.readyState="complete");Xa()}),Qa=p.getElementsByTagName("script")[0],Ya=Qa.parentNode;e.injectUrl=function(a,c,b){Oa();
var b=b.node=p.createElement("script"),e=Pa(b,"load","onreadystatechange",function(a){var a=a||window.event,b=a.target||a.srcElement;if(a.type==="load"||/complete|loaded/.test(b.readyState))e(),c&&c()});b.type="text/javascript";b.charset="utf-8";b.src=a;Ya.insertBefore(b,Qa);return b};e.log=function(){try{for(var a=0;a<arguments.length;a++)console.log(arguments[a])}catch(c){}};e.trace=h;var Aa=function(a,c,j){var f=arguments.length,d=0,l=["require","exports","module"];d||(d=f==1?[0,l,a]:f==2?b(a)?
[0,a,c]:g(c)?[a,l,c]:[a,[],c]:[a,c,j]);e.trace("loader-define",d.slice(0,2));if((f=d[0]&&T(d[0]))&&!N[f.mid])ea(Ba(f,d[1],d[2]));else if(!u("ie-event-behavior")||ya)na.push(d);else{f=f||fa;if(!f)for(a in N)if((l=L[a])&&l.node&&l.node.readyState==="interactive"){f=l;break}f?(ja(f),ea(Ba(f,d[1],d[2]))):H("error",q("ieDefineFailed",d[0]));X()}};Aa.amd={vendor:"dojotoolkit.org"};l(l(e,i.loaderPatch),a.loaderPatch);U("error",function(a){try{if(console.error(a),a instanceof Error){for(var c in a)console.log(c+
":",a[c]);console.log(".")}}catch(b){}});l(e,{uid:c,cache:ca,packs:O});j.define?H("error",q("defineAlreadyDefined",0)):(j.define=Aa,j.require=e);P=i.deps||a.deps||B.deps;B=i.deps||a.callback||B.callback;e.boot=P||B?[P||[],B]:0})(this.dojoConfig||this.djConfig||this.require||{},{async:0,hasCache:{"config-selectorEngine":"acme","dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../dojox",name:"dojox"},{location:"../dijit",name:"dijit"},{location:".",name:"dojo"},{location:"../uman",
name:"uman"}]});
require({cache:{"dojo/_base/fx":function(){define(["./kernel","./lang","../Evented","./Color","./connect","./sniff","../dom","../dom-style"],function(a,i,k,o,h,d,m,g){var n=i.mixin;a._Line=function(a,b){this.start=a;this.end=b};a._Line.prototype.getValue=function(a){return(this.end-this.start)*a+this.start};a.Animation=function(c){n(this,c);if(i.isArray(this.curve))this.curve=new a._Line(this.curve[0],this.curve[1])};a.Animation.prototype=new k;a._Animation=a.Animation;i.extend(a.Animation,{duration:350,
repeat:0,rate:20,_percent:0,_startRepeatCount:0,_getStep:function(){var a=this._percent,b=this.easing;return b?b(a):a},_fire:function(c,b){var j=b||[];if(this[c])if(a.config.debugAtAllCosts)this[c].apply(this,j);else try{this[c].apply(this,j)}catch(f){console.error("exception in animation handler for:",c),console.error(f)}return this},play:function(a,b){this._delayTimer&&this._clearTimer();if(b)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;
this._fire("beforeBegin",[this.node]);var j=a||this.delay,f=i.hitch(this,"_play",b);if(j>0)return this._delayTimer=setTimeout(f,j),this;f();return this},_play:function(){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);this._active=!0;this._paused=!1;var a=this.curve.getValue(this._getStep());if(!this._percent){if(!this._startRepeatCount)this._startRepeatCount=this.repeat;this._fire("onBegin",[a])}this._fire("onPlay",
[a]);this._cycle();return this},pause:function(){this._delayTimer&&this._clearTimer();this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,b){this._stopTimer();this._active=this._paused=!0;this._percent=a;b&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();if(a)this._percent=1;this._fire("onStop",[this.curve.getValue(this._getStep())]);
this._active=this._paused=!1;return this},status:function(){if(this._active)return this._paused?"paused":"playing";return"stopped"},_cycle:function(){if(this._active){var a=((new Date).valueOf()-this._startTime)/this.duration;a>=1&&(a=1);this._percent=a;this.easing&&(a=this.easing(a));this._fire("onAnimate",[this.curve.getValue(a)]);if(this._percent<1)this._startTimer();else{this._active=!1;if(this.repeat>0)this.repeat--,this.play(null,!0);else if(this.repeat==-1)this.play(null,!0);else if(this._startRepeatCount)this.repeat=
this._startRepeatCount,this._startRepeatCount=0;this._percent=0;this._fire("onEnd",[this.node]);!this.repeat&&this._stopTimer()}}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var b=0,f=null,l={run:function(){}};i.extend(a.Animation,{_startTimer:function(){if(!this._timer)this._timer=h.connect(l,"run",this,"_cycle"),b++;f||(f=setInterval(i.hitch(l,"run"),this.rate))},_stopTimer:function(){if(this._timer)h.disconnect(this._timer),this._timer=null,b--;
b<=0&&(clearInterval(f),f=null,b=0)}});var q=d("ie")?function(a){var b=a.style;if(!b.width.length&&g.get(a,"width")=="auto")b.width="auto"}:function(){};a._fade=function(c){c.node=m.byId(c.node);var b=n({properties:{}},c),c=b.properties.opacity={};c.start=!("start"in b)?function(){return+g.get(b.node,"opacity")||0}:b.start;c.end=b.end;c=a.animateProperty(b);h.connect(c,"beforeBegin",i.partial(q,b.node));return c};a.fadeIn=function(c){return a._fade(n({end:1},c))};a.fadeOut=function(c){return a._fade(n({end:0},
c))};a._defaultEasing=function(a){return 0.5+Math.sin((a+1.5)*Math.PI)/2};var r=function(a){this._properties=a;for(var b in a){var j=a[b];if(j.start instanceof o)j.tempColor=new o}};r.prototype.getValue=function(a){var b={},j;for(j in this._properties){var f=this._properties[j],d=f.start;d instanceof o?b[j]=o.blendColors(d,f.end,a,f.tempColor).toCss():i.isArray(d)||(b[j]=(f.end-d)*a+d+(j!="opacity"?f.units||"px":0))}return b};a.animateProperty=function(b){var e=b.node=m.byId(b.node);if(!b.easing)b.easing=
a._defaultEasing;b=new a.Animation(b);h.connect(b,"beforeBegin",b,function(){var a={},b;for(b in this.properties){if(b=="width"||b=="height")this.node.display="block";var c=this.properties[b];i.isFunction(c)&&(c=c(e));c=a[b]=n({},i.isObject(c)?c:{end:c});if(i.isFunction(c.start))c.start=c.start(e);if(i.isFunction(c.end))c.end=c.end(e);var f=b.toLowerCase().indexOf("color")>=0,d=function(a,b){var c={height:a.offsetHeight,width:a.offsetWidth}[b];if(c!==void 0)return c;c=g.get(a,b);return b=="opacity"?
+c:f?c:parseFloat(c)};if("end"in c){if(!("start"in c))c.start=d(e,b)}else c.end=d(e,b);f?(c.start=new o(c.start),c.end=new o(c.end)):c.start=b=="opacity"?+c.start:parseFloat(c.start)}this.curve=new r(a)});h.connect(b,"onAnimate",i.hitch(g,"set",b.node));return b};a.anim=function(b,e,j,f,d,l){return a.animateProperty({node:b,duration:j||a.Animation.prototype.duration,properties:e,easing:f,onEnd:d}).play(l||0)};return{_Line:a._Line,Animation:a.Animation,_fade:a._fade,fadeIn:a.fadeIn,fadeOut:a.fadeOut,
_defaultEasing:a._defaultEasing,animateProperty:a.animateProperty,anim:a.anim}})},"dojo/dom-form":function(){define("dojo/dom-form",["./_base/lang","./dom","./io-query","./json"],function(a,i,k,o){var h={fieldToObject:function(a){var h=null;if(a=i.byId(a)){var g=a.name,n=(a.type||"").toLowerCase();if(g&&n&&!a.disabled)if(n=="radio"||n=="checkbox"){if(a.checked)h=a.value}else if(a.multiple){h=[];for(a=[a.firstChild];a.length;)for(g=a.pop();g;g=g.nextSibling)if(g.nodeType==1&&g.tagName.toLowerCase()==
"option")g.selected&&h.push(g.value);else{g.nextSibling&&a.push(g.nextSibling);g.firstChild&&a.push(g.firstChild);break}}else h=a.value}return h},toObject:function(d){for(var m={},d=i.byId(d).elements,g=0,n=d.length;g<n;++g){var b=d[g],f=b.name,l=(b.type||"").toLowerCase();if(f&&l&&"file|submit|image|reset|button".indexOf(l)<0&&!b.disabled){var q=m,r=f,b=h.fieldToObject(b);if(b!==null){var c=q[r];typeof c=="string"?q[r]=[c,b]:a.isArray(c)?c.push(b):q[r]=b}if(l=="image")m[f+".x"]=m[f+".y"]=m[f].x=
m[f].y=0}}return m},toQuery:function(a){return k.objectToQuery(h.toObject(a))},toJson:function(a,m){return o.stringify(h.toObject(a),null,m?4:0)}};return h})},"dojo/_base/html":function(){define(["./kernel","../dom","../dom-style","../dom-attr","../dom-prop","../dom-class","../dom-construct","../dom-geometry"],function(a,i,k,o,h,d,m,g){a.byId=i.byId;a.isDescendant=i.isDescendant;a.setSelectable=i.setSelectable;a.getAttr=o.get;a.setAttr=o.set;a.hasAttr=o.has;a.removeAttr=o.remove;a.getNodeProp=o.getNodeProp;
a.attr=function(a,b,f){if(arguments.length==2)return o[typeof b=="string"?"get":"set"](a,b);return o.set(a,b,f)};a.hasClass=d.contains;a.addClass=d.add;a.removeClass=d.remove;a.toggleClass=d.toggle;a.replaceClass=d.replace;a._toDom=a.toDom=m.toDom;a.place=m.place;a.create=m.create;a.empty=function(a){m.empty(a)};a._destroyElement=a.destroy=function(a){m.destroy(a)};a._getPadExtents=a.getPadExtents=g.getPadExtents;a._getBorderExtents=a.getBorderExtents=g.getBorderExtents;a._getPadBorderExtents=a.getPadBorderExtents=
g.getPadBorderExtents;a._getMarginExtents=a.getMarginExtents=g.getMarginExtents;a._getMarginSize=a.getMarginSize=g.getMarginSize;a._getMarginBox=a.getMarginBox=g.getMarginBox;a.setMarginBox=g.setMarginBox;a._getContentBox=a.getContentBox=g.getContentBox;a.setContentSize=g.setContentSize;a._isBodyLtr=a.isBodyLtr=g.isBodyLtr;a._docScroll=a.docScroll=g.docScroll;a._getIeDocumentElementOffset=a.getIeDocumentElementOffset=g.getIeDocumentElementOffset;a._fixIeBiDiScrollLeft=a.fixIeBiDiScrollLeft=g.fixIeBiDiScrollLeft;
a.position=g.position;a.marginBox=function(a,b){return b?g.setMarginBox(a,b):g.getMarginBox(a)};a.contentBox=function(a,b){return b?g.setContentSize(a,b):g.getContentBox(a)};a.coords=function(d,b){a.deprecated("dojo.coords()","Use dojo.position() or dojo.marginBox().");var d=i.byId(d),f=k.getComputedStyle(d),f=g.getMarginBox(d,f),l=g.position(d,b);f.x=l.x;f.y=l.y;return f};a.getProp=h.get;a.setProp=h.set;a.prop=function(a,b,f){if(arguments.length==2)return h[typeof b=="string"?"get":"set"](a,b);return h.set(a,
b,f)};a.getStyle=k.get;a.setStyle=k.set;a.getComputedStyle=k.getComputedStyle;a.__toPixelValue=a.toPixelValue=k.toPixelValue;a.style=function(a,b,f){switch(arguments.length){case 1:return k.get(a);case 2:return k[typeof b=="string"?"get":"set"](a,b)}return k.set(a,b,f)};return a})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(a,i,k,o){var h,d={},m={},g={config:i,global:this,dijit:d,dojox:m},d={dojo:["dojo",g],dijit:["dijit",d],dojox:["dojox",m]},o=k.packs&&
k.packs[o.id.match(/[^\/]+/)[0]].packageMap||{};for(h in o)d[h]?d[h][0]=o[h]:d[h]=[o[h],{}];for(h in d)o=d[h],o[1]._scopeName=o[0],i.noGlobals||(this[o[0]]=o[1]);g.scopeMap=d;g.baseUrl=g.config.baseUrl=k.baseUrl;g.isAsync=k.async;g.locale=i.locale;o="$Rev: 27407 $".match(/\d+/);g.version={major:1,minor:7,patch:1,flag:"",revision:o?+o[0]:NaN,toString:function(){var a=g.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};g.eval=k.eval;g.exit=function(){};typeof console!="undefined"||
(console={});for(var d=["assert","count","debug","dir","dirxml","error","group","groupEnd","info","profile","profileEnd","time","timeEnd","trace","warn","log"],n,o=0;n=d[o++];)console[n]||function(){var a=n+"";console[a]="log"in console?function(){var f=Array.apply({},arguments);f.unshift(a+":");console.log(f.join(" "))}:function(){};console[a]._fake=!0}();a.add("dojo-debug-messages",!!i.isDebug);a("dojo-debug-messages")?(g.deprecated=function(a,f,d){a="DEPRECATED: "+a;f&&(a+=" "+f);d&&(a+=" -- will be removed in version: "+
d);console.warn(a)},g.experimental=function(a,f){var d="EXPERIMENTAL: "+a+" -- APIs subject to change without notice.";f&&(d+=" "+f);console.warn(d)}):g.deprecated=g.experimental=function(){};if(i.modulePaths){g.deprecated("dojo.modulePaths","use paths configuration");a={};for(h in i.modulePaths)a[h.replace(/\./g,"/")]=i.modulePaths[h];k({paths:a})}g.moduleUrl=function(a,f){g.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var d=null;a&&(d=k.toUrl(a.replace(/\./g,"/")+(f?"/"+f:"")+"/*.*").replace(/\/\*\.\*/,
"")+(f?"":"/"));return d};g._hasResource={};return g})},"dojo/io-query":function(){define(["./_base/lang"],function(a){var i={};return{objectToQuery:function(k){var o=encodeURIComponent,h=[],d;for(d in k){var m=k[d];if(m!=i[d]){var g=o(d)+"=";if(a.isArray(m))for(var n=0,b=m.length;n<b;++n)h.push(g+o(m[n]));else h.push(g+o(m))}}return h.join("&")},queryToObject:function(k){for(var i=decodeURIComponent,k=k.split("&"),h={},d,m,g=0,n=k.length;g<n;++g)if(m=k[g],m.length){var b=m.indexOf("=");b<0?(d=i(m),
m=""):(d=i(m.slice(0,b)),m=i(m.slice(b+1)));typeof h[d]=="string"&&(h[d]=[h[d]]);a.isArray(h[d])?h[d].push(m):h[d]=m}return h}}})},"dojo/_base/Deferred":function(){define("dojo/_base/Deferred",["./kernel","./lang"],function(a,i){var k=function(){},o=Object.freeze||function(){};a.Deferred=function(h){function d(a){if(n)throw Error("This deferred has already been resolved");g=a;n=!0;m()}function m(){for(var a;!a&&l;){var e=l;l=l.next;if(a=e.progress==k)n=!1;var j=b?e.error:e.resolved;if(j)try{var f=
j(g);f&&typeof f.then==="function"?f.then(i.hitch(e.deferred,"resolve"),i.hitch(e.deferred,"reject"),i.hitch(e.deferred,"progress")):(j=a&&f===void 0,a&&!j&&(b=f instanceof Error),e.deferred[j&&b?"reject":"resolve"](j?g:f))}catch(d){e.deferred.reject(d)}else b?e.deferred.reject(g):e.deferred.resolve(g)}}var g,n,b,f,l,q=this.promise={};this.resolve=this.callback=function(a){this.fired=0;this.results=[a,null];d(a)};this.reject=this.errback=function(c){b=!0;this.fired=1;d(c);this.results=[null,c];if(!c||
c.log!==!1)(a.config.deferredOnError||function(a){console.error(a)})(c)};this.progress=function(a){for(var b=l;b;){var j=b.progress;j&&j(a);b=b.next}};this.addCallbacks=function(a,b){this.then(a,b,k);return this};q.then=this.then=function(b,e,j){var d=j==k?this:new a.Deferred(q.cancel),b={resolved:b,error:e,progress:j,deferred:d};l?f=f.next=b:l=f=b;n&&m();return d.promise};var r=this;q.cancel=this.cancel=function(){if(!n){var a=h&&h(r);if(!n)a instanceof Error||(a=Error(a)),a.log=!1,r.reject(a)}};
o(q)};i.extend(a.Deferred,{addCallback:function(){return this.addCallbacks(i.hitch.apply(a,arguments))},addErrback:function(){return this.addCallbacks(null,i.hitch.apply(a,arguments))},addBoth:function(){var h=i.hitch.apply(a,arguments);return this.addCallbacks(h,h)},fired:-1});a.Deferred.when=a.when=function(a,d,m,g){if(a&&typeof a.then==="function")return a.then(d,m,g);return d?d(a):a};return a.Deferred})},"dojo/NodeList-dom":function(){define(["./_base/kernel","./query","./_base/array","./_base/lang",
"./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],function(a,i,k,o,h,d,m,g,n){function b(a){return function(b,c,e){if(arguments.length==2)return a[typeof c=="string"?"get":"set"](b,c);return a.set(b,c,e)}}var f=function(a){return a.length==1&&typeof a[0]=="string"},l=function(a){var b=a.parentNode;b&&b.removeChild(a)},q=i.NodeList,r=q._adaptWithCondition,c=q._adaptAsForEach,e=q._adaptAsMap;o.extend(q,{_normalize:function(b,c){var e=b.parse===!0;if(typeof b.template=="string")var f=
b.templateFunc||a.string&&a.string.substitute,b=f?f(b.template,b):b;f=typeof b;f=="string"||f=="number"?(b=d.toDom(b,c&&c.ownerDocument),b=b.nodeType==11?o._toArray(b.childNodes):[b]):o.isArrayLike(b)?o.isArray(b)||(b=o._toArray(b)):b=[b];if(e)b._runParse=!0;return b},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(b,c,e,f){if(!(c.nodeType!=1&&e=="only"))for(var l,g=b.length,h=g-1;h>=0;h--){var q=f?this._cloneNode(b[h]):b[h];if(b._runParse&&a.parser&&a.parser.parse){l||(l=c.ownerDocument.createElement("div"));
l.appendChild(q);a.parser.parse(l);for(q=l.firstChild;l.firstChild;)l.removeChild(l.firstChild)}h==g-1?d.place(q,c,e):c.parentNode.insertBefore(q,c);c=q}},attr:r(b(g),f),style:r(b(n),f),addClass:c(h.add),removeClass:c(h.remove),replaceClass:c(h.replace),toggleClass:c(h.toggle),empty:c(d.empty),removeAttr:c(g.remove),position:e(m.position),marginBox:e(m.getMarginBox),place:function(a,b){var c=i(a)[0];return this.forEach(function(a){d.place(a,c,b)})},orphan:function(a){return(a?i._filterResult(this,
a):this).forEach(l)},adopt:function(a,b){return i(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=new q;this.map(function(c){i(a,c).forEach(function(a){a!==void 0&&b.push(a)})});return b._stash(this)},filter:function(a){var b=arguments,c=this,e=0;if(typeof a=="string"){c=i._filterResult(this,b[0]);if(b.length==1)return c._stash(this);e=1}return this._wrap(k.filter(c,b[e],b[e+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,e;e=this[c];c++)this._place(a,
e,b,c>0);return this}});return q})},"dojo/query":function(){define(["./_base/kernel","./has","./dom","./on","./_base/array","./_base/lang","./selector/_loader","./selector/_loader!default"],function(a,i,k,o,h,d,m,g){function n(a,b){var c=function(c,e){if(typeof e=="string"&&(e=k.byId(e),!e))return new b([]);var f=typeof c=="string"?a(c,e):c.orphan?c:[c];if(f.orphan)return f;return new b(f)};c.matches=a.match||function(a,b,e){return c.filter([a],b,e).length>0};c.filter=a.filter||function(a,b,e){return c(b,
e).filter(function(b){return h.indexOf(a,b)>-1})};if(typeof a!="function")var e=a.search,a=function(a,b){return e(b||document,a)};return c}i.add("array-extensible",function(){return d.delegate([],{length:1}).length==1&&!i("bug-for-in-skips-shadowed")});var b=Array.prototype,f=b.slice,l=b.concat,q=h.forEach,r=function(b,c,e){c=[0].concat(f.call(c,0));e=e||a.global;return function(a){c[0]=a;return b.apply(e,c)}},c=function(a){var b=this instanceof e&&i("array-extensible");typeof a=="number"&&(a=Array(a));
var c=a&&"length"in a?a:arguments;if(b||!c.sort){for(var f=b?this:[],l=f.length=c.length,g=0;g<l;g++)f[g]=c[g];if(b)return f;c=f}d._mixin(c,j);c._NodeListCtor=function(a){return e(a)};return c},e=c,j=e.prototype=i("array-extensible")?[]:{};e._wrap=j._wrap=function(a,b,c){a=new (c||this._NodeListCtor||e)(a);return b?a._stash(b):a};e._adaptAsMap=function(a,b){return function(){return this.map(r(a,arguments,b))}};e._adaptAsForEach=function(a,b){return function(){this.forEach(r(a,arguments,b));return this}};
e._adaptAsFilter=function(a,b){return function(){return this.filter(r(a,arguments,b))}};e._adaptWithCondition=function(b,c,e){return function(){var f=arguments,d=r(b,f,e);if(c.call(e||a.global,f))return this.map(d);this.forEach(d);return this}};q(["slice","splice"],function(a){var c=b[a];j[a]=function(){return this._wrap(c.apply(this,arguments),a=="slice"?this:null)}});q(["indexOf","lastIndexOf","every","some"],function(b){var c=h[b];j[b]=function(){return c.apply(a,[this].concat(f.call(arguments,
0)))}});d.extend(c,{constructor:e,_NodeListCtor:e,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return o(c,a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(){var a=d.isArray(this)?this:f.call(this,0),b=h.map(arguments,function(a){return a&&!d.isArray(a)&&(typeof c!="undefined"&&a.constructor===
c||a.constructor===this._NodeListCtor)?f.call(a,0):a});return this._wrap(l.apply(a,b),this)},map:function(a,b){return this._wrap(h.map(this,a,b),this)},forEach:function(a,b){q(this,a,b);return this},filter:function(a){var b=arguments,c=this,e=0;if(typeof a=="string"){c=p._filterResult(this,b[0]);if(b.length==1)return c._stash(this);e=1}return this._wrap(h.filter(c,b[e],b[e+1]),this)},instantiate:function(a,b){var c=d.isFunction(a)?a:d.getObject(a),b=b||{};return this.forEach(function(a){new c(b,a)})},
at:function(){var a=new this._NodeListCtor(0);q(arguments,function(b){b<0&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var p=n(g,c);a.query=n(g,function(a){return c(a)});p.load=function(a,b,e){m.load(a,b,function(a){e(n(a,c))})};a._filterQueryResult=p._filterResult=function(a,b,e){return new c(p.filter(a,b,e))};a.NodeList=p.NodeList=c;return p})},"dojo/has":function(){define(["require"],function(a){var i=a.has||function(){},a=navigator.userAgent;i.add("dom-addeventlistener",
!!document.addEventListener);i.add("touch","ontouchstart"in document);i.add("device-width",screen.availWidth||innerWidth);i.add("agent-ios",!!a.match(/iPhone|iP[ao]d/));i.add("agent-android",a.indexOf("android")>1);i.clearElement=function(a){a.innerHTML="";return a};i.normalize=function(a,o){var h=a.match(/[\?:]|[^:\?]*/g),d=0,m=function(a){var n=h[d++];if(n==":")return 0;else{if(h[d++]=="?")return!a&&i(n)?m():(m(!0),m(a));return n||0}};return(a=m())&&o(a)};i.load=function(a,i,h){a?i([a],h):h()};
return i})},"dojo/_base/loader":function(){define(["./kernel","../has","require","module","./json","./lang","./array"],function(a,i,k,o,h,d,m){var g=function(a){return a.replace(/\./g,"/")},n=/\/\/>>built/,b=[],f=[],l=function(){f=m.filter(f,function(a){return a.injected!==u&&!a.executed});if(!f.length){p.holdIdle();var a=b;b=[];m.forEach(a,function(a){a(1)});p.releaseIdle()}},q=function(b,c,e){var f=/\(|\)/g,d=1;for(f.lastIndex=c;c=f.exec(b);)if(c[0]==")"?d-=1:d+=1,d==0)break;if(d!=0)throw"unmatched paren around character "+
f.lastIndex+" in: "+b;return[a.trim(b.substring(e,f.lastIndex))+";\n",f.lastIndex]},r=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,c=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,e=/(^|\s)(require|define)\s*\(/m,j=function(a,b){var f,d,j,l=[],g=[];f=[];for(b=b||a.replace(r,function(a){c.lastIndex=e.lastIndex=0;return c.test(a)||e.test(a)?"":a});f=c.exec(b);)d=c.lastIndex,j=d-f[0].length,d=q(b,d,j),f[2]=="loadInit"?l.push(d[0]):g.push(d[0]),c.lastIndex=
d[1];f=l.concat(g);return f.length||!e.test(b)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),f.join(""),f]:0},p=k.initSyncLoader(function(a,c,e){b.push(e);m.forEach(a.split(","),function(a){a=D(a,c.module);f.push(a);S(a)});l()},l,function(b,c){var e,f,d=[],l=[];if(n.test(c)||!(e=j(c)))return 0;f=b.mid+"-*loadInit";for(var g in D("dojo",b).result.scopeMap)d.push(g),l.push('"'+g+'"');return"// xdomain rewrite of "+b.path+"\ndefine('"+f+"',{\n\tnames:"+a.toJson(d)+",\n\tdef:function("+
d.join(",")+"){"+e[1]+"}});\n\ndefine("+a.toJson(d.concat(["dojo/loadInit!"+f]))+", function("+d.join(",")+"){\n"+e[0]+"});"}),t=p.sync,u=p.arrived,s=p.nonmodule,B=p.executing,w=p.executed,C=p.syncExecStack,J=p.execQ,D=p.getModule,S=p.injectModule,Q=p.setArrived,ba=p.signal,v=p.finishExec,z=p.execModule,E=p.getLegacyMode;a.provide=function(a){var b=C[0],c=d.mixin(D(g(a),k.module),{executed:B,result:d.getObject(a,!0)});Q(c);if(b)(b.provides||(b.provides=[])).push(function(){c.result=d.getObject(a);
delete c.provides;c.executed!==w&&v(c)});return c.result};i.add("config-publishRequireResult",1,0,0);a.require=function(a,b){var c=function(a,b){var c=D(g(a),k.module);if(C.length&&C[0].finish)C[0].finish.push(a);else{if(c.executed)return c.result;b&&(c.result=s);var e=E();S(c);e=E();c.executed!==w&&c.injected===u&&(p.holdIdle(),z(c),p.releaseIdle());if(c.executed)return c.result;e==t?c.cjs?J.unshift(c):C.length&&(C[0].finish=[a]):J.push(c)}}(a,b);i("config-publishRequireResult")&&!d.exists(a)&&c!==
void 0&&d.setObject(a,c);return c};a.loadInit=function(a){a()};a.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;k({paths:c})};a.platformRequire=function(b){for(var b=(b.common||[]).concat(b[a._name]||b["default"]||[]),c;b.length;)d.isArray(c=b.shift())?a.require.apply(a,c):a.require(c)};a.requireIf=a.requireAfterIf=function(b,c,e){b&&a.require(c,e)};a.requireLocalization=function(a,b,c){k(["../i18n"],function(e){e.getLocalization(a,b,c)})};return{extractLegacyApiApplications:j,
require:p.dojoRequirePlugin,loadInit:function(c,e,d){e([c],function(c){e(c.names,function(){for(var j="",h=[],q=0;q<arguments.length;q++)j+="var "+c.names[q]+"= arguments["+q+"]; ",h.push(arguments[q]);eval(j);var n=e.module,r=[],j={},i=[],p,q={provide:function(a){a=g(a);a=D(a,n);a!==n&&Q(a)},require:function(a,b){a=g(a);b&&(D(a,n).result=s);i.push(a)},requireLocalization:function(b,c,e){r.length||(r=["dojo/i18n"]);e=(e||a.locale).toLowerCase();b=g(b)+"/nls/"+(/root/i.test(e)?"":e+"/")+g(c);D(b,n).isXd&&
r.push("dojo/i18n!"+b)},loadInit:function(a){a()}};try{for(p in q)j[p]=a[p],a[p]=q[p];c.def.apply(null,h)}catch(k){ba("error",[{src:o.id,id:"failedDojoLoadInit"},k])}finally{for(p in q)a[p]=j[p]}i.length&&r.push("dojo/require!"+i.join(","));b.push(d);m.forEach(i,function(a){a=D(a,e.module);f.push(a);S(a)});l()})})}}})},"dojo/json":function(){define(["./has"],function(a){var i=typeof JSON!="undefined";a.add("json-parse",i);a.add("json-stringify",i&&JSON.stringify({a:0},function(a,h){return h||1})==
'{"a":1}');if(a("json-stringify"))return JSON;else{var k=function(a){return('"'+a.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:a("json-parse")?JSON.parse:function(a,h){if(h&&!/^([\s\[\{]*(?:"(?:\\.|[^"])+"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(a))throw new SyntaxError("Invalid characters in JSON");return eval("("+a+")")},stringify:function(a,h,d){function m(a,
b,f){h&&(a=h(f,a));var l;l=typeof a;if(l=="number")return isFinite(a)?a+"":"null";if(l=="boolean")return a+"";if(a===null)return"null";if(typeof a=="string")return k(a);if(l=="function"||l=="undefined")return g;if(typeof a.toJSON=="function")return m(a.toJSON(f),b,f);if(a instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(b,c,e){b=a["getUTC"+c]()+(e?1:0);return b<10?"0"+b:b});if(a.valueOf()!==a)return m(a.valueOf(),b,f);var q=d?b+d:
"",r=d?" ":"",c=d?"\n":"";if(a instanceof Array){for(var r=a.length,e=[],f=0;f<r;f++)l=m(a[f],q,f),typeof l!="string"&&(l="null"),e.push(c+q+l);return"["+e.join(",")+c+b+"]"}e=[];for(f in a){var j;if(typeof f=="number")j='"'+f+'"';else if(typeof f=="string")j=k(f);else continue;l=m(a[f],q,f);typeof l=="string"&&e.push(c+q+j+":"+r+l)}return"{"+e.join(",")+c+b+"}"}var g;typeof h=="string"&&(d=h,h=null);return m(a,"","")}}}})},"dojo/_base/declare":function(){define(["./kernel","../has","./lang"],function(a,
i,k){function o(a,b){throw Error("declare"+(b?" "+b:"")+": "+a);}function h(a,b,c){var e,f,d,j,l,g,h,q=this._inherited=this._inherited||{};typeof a=="string"&&(e=a,a=b,b=c);c=0;j=a.callee;(e=e||j.nom)||o("can't deduce a name to call inherited()",this.declaredClass);l=this.constructor._meta;d=l.bases;h=q.p;if(e!=w){if(q.c!==j&&(h=0,g=d[0],l=g._meta,l.hidden[e]!==j)){(f=l.chains)&&typeof f[e]=="string"&&o("calling chained method with inherited: "+e,this.declaredClass);do if(l=g._meta,f=g.prototype,
l&&(f[e]===j&&f.hasOwnProperty(e)||l.hidden[e]===j))break;while(g=d[++h]);h=g?h:-1}if(g=d[++h])if(f=g.prototype,g._meta&&f.hasOwnProperty(e))c=f[e];else{j=t[e];do if(f=g.prototype,(c=f[e])&&(g._meta?f.hasOwnProperty(e):c!==j))break;while(g=d[++h])}c=g&&c||t[e]}else{if(q.c!==j&&(h=0,(l=d[0]._meta)&&l.ctor!==j)){f=l.chains;for((!f||f.constructor!=="manual")&&o("calling chained constructor with inherited",this.declaredClass);g=d[++h];)if((l=g._meta)&&l.ctor===j)break;h=g?h:-1}for(;g=d[++h];)if(c=(l=
g._meta)?l.ctor:g)break;c=g&&c}q.c=c;q.p=h;if(c)return b===!0?c:c.apply(this,b||a)}function d(a,b){if(typeof a=="string")return this.__inherited(a,b,!0);return this.__inherited(a,!0)}function m(a,b,c){var e=this.getInherited(a,b);if(e)return e.apply(this,c||b||a)}function g(a){for(var b=this.constructor._meta.bases,c=0,e=b.length;c<e;++c)if(b[c]===a)return!0;return this instanceof a}function n(a,b){for(var c in b)c!=w&&b.hasOwnProperty(c)&&(a[c]=b[c]);if(i("bug-for-in-skips-shadowed"))for(var e=k._extraNames,
f=e.length;f;)c=e[--f],c!=w&&b.hasOwnProperty(c)&&(a[c]=b[c])}function b(a){j.safeMixin(this.prototype,a);return this}function f(a,b){return function(){var v;var c=arguments,f=c,d=c[0],j,l;l=a.length;var g;if(!(this instanceof c.callee))return e(c);if(b&&(d&&d.preamble||this.preamble)){g=Array(a.length);g[0]=c;for(j=0;;){if(d=c[0])(d=d.preamble)&&(c=d.apply(this,c)||c);d=a[j].prototype;(d=d.hasOwnProperty("preamble")&&d.preamble)&&(c=d.apply(this,c)||c);if(++j==l)break;g[j]=c}}for(j=l-1;j>=0;--j)d=
a[j],(v=(l=d._meta)?l.ctor:d,d=v)&&d.apply(this,g?g[j]:c);(d=this.postscript)&&d.apply(this,f)}}function l(a,b){return function(){var c=arguments,f=c,d=c[0];if(!(this instanceof c.callee))return e(c);if(b){if(d)(d=d.preamble)&&(f=d.apply(this,f)||f);(d=this.preamble)&&d.apply(this,f)}a&&a.apply(this,c);(d=this.postscript)&&d.apply(this,c)}}function q(a){return function(){var v;var b=arguments,c=0,f,d;if(!(this instanceof b.callee))return e(b);for(;f=a[c];++c)if(v=(d=f._meta)?d.ctor:f,f=v){f.apply(this,
b);break}(f=this.postscript)&&f.apply(this,b)}}function r(a,b,c){return function(){var e,f,d=0,j=1;c&&(d=b.length-1,j=-1);for(;e=b[d];d+=j)f=e._meta,(e=(f?f.hidden:e.prototype)[a])&&e.apply(this,arguments)}}function c(a){s.prototype=a.prototype;a=new s;s.prototype=null;return a}function e(a){var b=a.callee,e=c(b);b.apply(e,a);return e}function j(a,e,m){typeof a!="string"&&(m=e,e=a,a="");var m=m||{},i,s,v,z,E,A,F,K=1,H=e;if(u.call(e)=="[object Array]"){K=a;v=[];z=[{cls:0,refs:[]}];A={};for(var U=1,
V=e.length,I=0,y,O,x,G;I<V;++I){(y=e[I])?u.call(y)!="[object Function]"&&o("mixin #"+I+" is not a callable constructor.",K):o("mixin #"+I+" is unknown. Did you use dojo.require to pull it in?",K);O=y._meta?y._meta.bases:[y];x=0;for(y=O.length-1;y>=0;--y){G=O[y].prototype;if(!G.hasOwnProperty("declaredClass"))G.declaredClass="uniqName_"+B++;G=G.declaredClass;A.hasOwnProperty(G)||(A[G]={count:0,refs:[],cls:O[y]},++U);G=A[G];x&&x!==G&&(G.refs.push(x),++x.count);x=G}++x.count;z[0].refs.push(x)}for(;z.length;){x=
z.pop();v.push(x.cls);for(--U;s=x.refs,s.length==1;){x=s[0];if(!x||--x.count){x=0;break}v.push(x.cls);--U}if(x){I=0;for(V=s.length;I<V;++I)x=s[I],--x.count||z.push(x)}}U&&o("can't build consistent linearization",K);y=e[0];v[0]=y?y._meta&&y===v[v.length-y._meta.bases.length]?y._meta.bases.length:1:0;A=v;v=A[0];K=A.length-v;e=A[K]}else A=[0],e?u.call(e)=="[object Function]"?(v=e._meta,A=A.concat(v?v.bases:e)):o("base class is not a callable constructor.",a):e!==null&&o("unknown base class. Did you use dojo.require to pull it in?",
a);if(e)for(s=K-1;;--s){i=c(e);if(!s)break;v=A[s];(v._meta?n:p)(i,v.prototype);z=new Function;z.superclass=e;z.prototype=i;e=i.constructor=z}else i={};j.safeMixin(i,m);v=m.constructor;if(v!==t.constructor)v.nom=w,i.constructor=v;for(s=K-1;s;--s)(v=A[s]._meta)&&v.chains&&(F=p(F||{},v.chains));i["-chains-"]&&(F=p(F||{},i["-chains-"]));v=!F||!F.hasOwnProperty(w);A[0]=z=F&&F.constructor==="manual"?q(A):A.length==1?l(m.constructor,v):f(A,v);z._meta={bases:A,hidden:m,chains:F,parents:H,ctor:m.constructor};
z.superclass=e&&e.prototype;z.extend=b;z.prototype=i;i.constructor=z;i.getInherited=d;i.isInstanceOf=g;i.inherited=C;i.__inherited=h;if(a)i.declaredClass=a,k.setObject(a,z);if(F)for(E in F)if(i[E]&&typeof F[E]=="string"&&E!=w)v=i[E]=r(E,A,F[E]==="after"),v.nom=E;return z}var p=k.mixin,t=Object.prototype,u=t.toString,s=new Function,B=0,w="constructor",C=a.config.isDebug?m:h;a.safeMixin=j.safeMixin=function(a,b){var c,e;for(c in b)if(e=b[c],(e!==t[c]||!(c in t))&&c!=w){if(u.call(e)=="[object Function]")e.nom=
c;a[c]=e}if(i("bug-for-in-skips-shadowed"))for(var f=k._extraNames,d=f.length;d;)if(c=f[--d],e=b[c],(e!==t[c]||!(c in t))&&c!=w){if(u.call(e)=="[object Function]")e.nom=c;a[c]=e}return a};return a.declare=j})},"dojo/dom":function(){define(["./_base/sniff","./_base/lang","./_base/window"],function(a,i,k){try{document.execCommand("BackgroundImageCache",!1,!0)}catch(o){}var h={};h.byId=a("ie")?function(a,h){if(typeof a!="string")return a;var g=h||k.doc,i=a&&g.getElementById(a);if(i&&(i.attributes.id.value==
a||i.id==a))return i;else{g=g.all[a];if(!g||g.nodeName)g=[g];for(var b=0;i=g[b++];)if(i.attributes&&i.attributes.id&&i.attributes.id.value==a||i.id==a)return i}}:function(a,h){return(typeof a=="string"?(h||k.doc).getElementById(a):a)||null};h.isDescendant=function(a,i){try{a=h.byId(a);for(i=h.byId(i);a;){if(a==i)return!0;a=a.parentNode}}catch(g){}return!1};h.setSelectable=function(d,i){d=h.byId(d);if(a("mozilla"))d.style.MozUserSelect=i?"":"none";else if(a("khtml")||a("webkit"))d.style.KhtmlUserSelect=
i?"auto":"none";else if(a("ie"))for(var g=d.unselectable=i?"":"on",k=d.getElementsByTagName("*"),b=0,f=k.length;b<f;++b)k.item(b).unselectable=g};return h})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("dojo/_base/browser",["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(a){return a})},"dojo/selector/acme":function(){define(["../_base/kernel","../has","../dom","../_base/sniff",
"../_base/array","../_base/lang","../_base/window"],function(a,i,k){var o=a.trim,h=a.forEach,d=(a.isWebKit||a.isMozilla)&&a.doc.compatMode=="BackCompat",m=!1,g=function(){return!0},n=function(a){a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var b=function(b,c){return o(a.slice(b,c))},c=[],e=-1,f=-1,d=-1,j=-1,l=-1,g=-1,h=-1,q="",i="",r,p=0,k=a.length,n=null,s=null,J=function(){if(g>=0)n.id=b(g,p).replace(/\\/g,""),g=-1;if(h>=0){var a=h==p?null:b(h,p);n[">~+".indexOf(a)<0?"tag":"oper"]=a;h=-1}l>=0&&
(n.classes.push(b(l+1,p).replace(/\\/g,"")),l=-1)};q=i,i=a.charAt(p),p<k;p++)if(q!="\\")if(n||(r=p,n={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return m?this.otag:this.tag}},h=p),e>=0)if(i=="]"){s.attr?s.matchFor=b(d||e+1,p):s.attr=b(e+1,p);if((e=s.matchFor)&&(e.charAt(0)=='"'||e.charAt(0)=="'"))s.matchFor=e.slice(1,-1);n.attrs.push(s);s=null;e=d=-1}else{if(i=="=")d="|~^$*".indexOf(q)>=0?q:"",s.type=d+i,s.attr=b(e+1,p-d.length),d=p+1}else if(f>=0){if(i==
")"){if(j>=0)s.value=b(f+1,p);j=f=-1}}else if(i=="#")J(),g=p+1;else if(i==".")J(),l=p;else if(i==":")J(),j=p;else if(i=="[")J(),e=p,s={};else if(i=="(")j>=0&&(s={name:b(j+1,p),value:null},n.pseudos.push(s)),f=p;else if(i==" "&&q!=i){J();j>=0&&n.pseudos.push({name:b(j+1,p)});n.loops=n.pseudos.length||n.attrs.length||n.classes.length;n.oquery=n.query=b(r,p);n.otag=n.tag=n.oper?null:n.tag||"*";if(n.tag)n.tag=n.tag.toUpperCase();if(c.length&&c[c.length-1].oper)n.infixOper=c.pop(),n.query=n.infixOper.query+
" "+n.query;c.push(n);n=null}return c},b=function(a,b){if(!a)return b;if(!b)return a;return function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},f=function(a,b){var c=b||[];a&&c.push(a);return c},l=function(a){return 1==a.nodeType},q=function(a,b){if(!a)return"";if(b=="class")return a.className||"";if(b=="for")return a.htmlFor||"";if(b=="style")return a.style.cssText||"";return(m?a.getAttribute(b):a.getAttribute(b,2))||""},r={"*=":function(a,b){return function(c){return q(c,a).indexOf(b)>=
0}},"^=":function(a,b){return function(c){return q(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+q(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+q(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){var c=b+"-";return function(e){e=q(e,a);return e==b||e.indexOf(c)==0}},"=":function(a,b){return function(c){return q(c,a)==b}}},c=typeof a.doc.firstChild.nextElementSibling=="undefined",e=!c?"nextElementSibling":"nextSibling",
j=!c?"previousElementSibling":"previousSibling",p=c?l:g,t=function(a){for(;a=a[j];)if(p(a))return!1;return!0},u=function(a){for(;a=a[e];)if(p(a))return!1;return!0},s=function(a){var b=a.parentNode,c=0,f=b.children||b.childNodes,d=a._i||-1,j=b._l||-1;if(!f)return-1;f=f.length;if(j==f&&d>=0&&j>=0)return d;b._l=f;d=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[e])if(p(b))b._i=++c,a===b&&(d=c);return d},B=function(a){return!(s(a)%2)},w=function(a){return s(a)%2},C={checked:function(){return function(a){return!!("checked"in
a?a.checked:a.selected)}},"first-child":function(){return t},"last-child":function(){return u},"only-child":function(){return function(a){return t(a)&&u(a)}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==3)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=n(b)[0],e={el:1};if(c.tag!="*")e.tag=1;if(!c.classes.length)e.classes=
1;var f=D(c,e);return function(a){return!f(a)}},"nth-child":function(a,b){var c=parseInt;if(b=="odd")return w;else if(b=="even")return B;if(b.indexOf("n")!=-1){var e=b.split("n",2),f=e[0]?e[0]=="-"?-1:c(e[0]):1,d=e[1]?c(e[1]):0,j=0,l=-1;f>0?d<0?d=d%f&&f+d%f:d>0&&(d>=f&&(j=d-d%f),d%=f):f<0&&(f*=-1,d>0&&(l=d,d%=f));if(f>0)return function(a){a=s(a);return a>=j&&(l<0||a<=l)&&a%f==d};else b=d}var g=c(b);return function(a){return s(a)==g}}},J=a.isIE&&(a.isIE<9||a.isQuirks)?function(a){var b=a.toLowerCase();
b=="class"&&(a="className");return function(c){return m?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},D=function(a,c){if(!a)return g;var c=c||{},e=null;"el"in c||(e=b(e,l));"tag"in c||a.tag!="*"&&(e=b(e,function(b){return b&&b.tagName==a.getTag()}));"classes"in c||h(a.classes,function(a,c){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");e=b(e,function(a){return f.test(a.className)});e.count=c});"pseudos"in c||h(a.pseudos,function(a){var c=a.name;
C[c]&&(e=b(e,C[c](c,a.value)))});"attrs"in c||h(a.attrs,function(a){var c,f=a.attr;a.type&&r[a.type]?c=r[a.type](f,a.matchFor):f.length&&(c=J(f));c&&(e=b(e,c))});"id"in c||a.id&&(e=b(e,function(b){return!!b&&b.id==a.id}));e||"default"in c||(e=g);return e},S=function(a){return function(b,f,d){for(;b=b[e];)if(!c||l(b)){(!d||x(b,d))&&a(b)&&f.push(b);break}return f}},Q=function(a){return function(b,c,f){for(b=b[e];b;){if(p(b)){if(f&&!x(b,f))break;a(b)&&c.push(b)}b=b[e]}return c}},ba=function(a){a=a||
g;return function(b,c,e){for(var f=0,d=b.children||b.childNodes;b=d[f++];)p(b)&&(!e||x(b,e))&&a(b,f)&&c.push(b);return c}},v={},z=function(b){var c=v[b.query];if(c)return c;var e=b.infixOper,e=e?e.oper:"",j=D(b,{el:1}),l="*"==b.tag,h=a.doc.getElementsByClassName;if(e){h={el:1};if(l)h.tag=1;j=D(b,h);"+"==e?c=S(j):"~"==e?c=Q(j):">"==e&&(c=ba(j))}else if(b.id)j=!b.loops&&l?g:D(b,{el:1,id:1}),c=function(a,c){var e=k.byId(b.id,a.ownerDocument||a);if(e&&j(e))if(9==a.nodeType)return f(e,c);else{for(var d=
e.parentNode;d;){if(d==a)break;d=d.parentNode}if(d)return f(e,c)}};else if(h&&/\{\s*\[native code\]\s*\}/.test(String(h))&&b.classes.length&&!d)var j=D(b,{el:1,classes:1,id:1}),i=b.classes.join(" "),c=function(a,b,c){for(var b=f(0,b),e,d=0,l=a.getElementsByClassName(i);e=l[d++];)j(e,a)&&x(e,c)&&b.push(e);return b};else!l&&!b.loops?c=function(a,c,e){for(var c=f(0,c),d=0,j=a.getElementsByTagName(b.getTag());a=j[d++];)x(a,e)&&c.push(a);return c}:(j=D(b,{el:1,tag:1,id:1}),c=function(a,c,e){for(var c=
f(0,c),d,l=0,g=a.getElementsByTagName(b.getTag());d=g[l++];)j(d,a)&&x(d,e)&&c.push(d);return c});return v[b.query]=c},E={},A={},F=function(a){var b=n(o(a));if(b.length==1){var c=z(b[0]);return function(a){if(a=c(a,[]))a.nozip=!0;return a}}return function(a){for(var a=f(a),c,e,d=b.length,j,l,g=0;g<d;g++){l=[];c=b[g];e=a.length-1;if(e>0)j={},l.nozip=!0;e=z(c);for(var h=0;c=a[h];h++)e(c,l,j);if(!l.length)break;a=l}return l}},i=navigator.userAgent,i=a.isWebKit&&i.indexOf("WebKit/")>0&&parseFloat(i.split("WebKit/")[1])>
528,K=a.isIE?"commentStrip":"nozip",H=!!a.doc.querySelectorAll&&(!a.isSafari||a.isSafari>3.1||i),U=/n\+\d|([^ ])?([>~+])([^ =])?/g,V=function(a,b,c,e){return c?(b?b+" ":"")+c+(e?" "+e:""):a},I=function(b,c){b=b.replace(U,V);if(H){var e=A[b];if(e&&!c)return e}if(e=E[b])return e;var e=b.charAt(0),f=-1==b.indexOf(" ");b.indexOf("#")>=0&&f&&(c=!0);if(H&&!c&&">~+".indexOf(e)==-1&&(!a.isIE||b.indexOf(":")==-1)&&!(d&&b.indexOf(".")>=0)&&b.indexOf(":contains")==-1&&b.indexOf(":checked")==-1&&b.indexOf("|=")==
-1){var j=">~+".indexOf(b.charAt(b.length-1))>=0?b+" *":b;return A[b]=function(a){try{if(!(9==a.nodeType||f))throw"";var c=a.querySelectorAll(j);c[K]=!0;return c}catch(e){return I(b,!0)(a)}}}else{var l=b.split(/\s*,\s*/);return E[b]=l.length<2?F(b):function(a){for(var b=0,c=[],e;e=l[b++];)c=c.concat(F(e)(a));return c}}},y=0,O=a.isIE?function(a){return m?a.getAttribute("_uid")||a.setAttribute("_uid",++y)||y:a.uniqueID}:function(a){return a._uid||(a._uid=++y)},x=function(a,b){if(!b)return 1;var c=O(a);
if(!b[c])return b[c]=1;return 0},G=function(b){if(b&&b.nozip)return b;var c=[];if(!b||!b.length)return c;b[0]&&c.push(b[0]);if(b.length<2)return c;y++;if(a.isIE&&m){var e=y+"";b[0].setAttribute("_zipIdx",e);for(var f=1,d;d=b[f];f++)b[f].getAttribute("_zipIdx")!=e&&c.push(d),d.setAttribute("_zipIdx",e)}else if(a.isIE&&b.commentStrip)try{for(f=1;d=b[f];f++)l(d)&&c.push(d)}catch(j){}else{b[0]&&(b[0]._zipIdx=y);for(f=1;d=b[f];f++)b[f]._zipIdx!=y&&c.push(d),d._zipIdx=y}return c},i=function(b,c){var c=
c||a.doc,e=c.ownerDocument||c.documentElement;m=c.contentType&&c.contentType=="application/xml"||a.isOpera&&(c.doctype||e.toString()=="[object XMLDocument]")||!!e&&(a.isIE?e.xml:c.xmlVersion||e.xmlVersion);if((e=I(b)(c))&&e.nozip)return e;return G(e)};i.filter=function(b,c,e){for(var f=[],d=n(c),d=d.length==1&&!/[^\w#\.]/.test(c)?D(d[0]):function(b){return a.query(c,e).indexOf(b)!=-1},j=0,l;l=b[j];j++)d(l)&&f.push(l);return f};return i})},"dojo/dom-style":function(){define(["./_base/sniff","./dom"],
function(a,i){function k(l,c,e){c=c.toLowerCase();if(a("ie")){if(e=="auto"){if(c=="height")return l.offsetHeight;if(c=="width")return l.offsetWidth}if(c=="fontweight")switch(e){case 700:return"bold";default:return"normal"}}c in b||(b[c]=f.test(c));return b[c]?d(l,e):e}var o,h={};o=a("webkit")?function(a){var b;if(a.nodeType==1){var e=a.ownerDocument.defaultView;b=e.getComputedStyle(a,null);if(!b&&a.style)a.style.display="",b=e.getComputedStyle(a,null)}return b||{}}:a("ie")&&(a("ie")<9||a("quirks"))?
function(a){return a.nodeType==1?a.currentStyle:{}}:function(a){return a.nodeType==1?a.ownerDocument.defaultView.getComputedStyle(a,null):{}};h.getComputedStyle=o;var d;d=a("ie")?function(a,b){if(!b)return 0;if(b=="medium")return 4;if(b.slice&&b.slice(-2)=="px")return parseFloat(b);var e=a.style,f=a.runtimeStyle,d=e.left,l=f.left;f.left=a.currentStyle.left;try{e.left=b,b=e.pixelLeft}catch(g){b=0}e.left=d;f.left=l;return b}:function(a,b){return parseFloat(b)||0};h.toPixelValue=d;var m=function(a,b){try{return a.filters.item("DXImageTransform.Microsoft.Alpha")}catch(e){return b?
{}:null}},g=a("ie")<9||a("ie")&&a("quirks")?function(a){try{return m(a).Opacity/100}catch(b){return 1}}:function(a){return o(a).opacity},n=a("ie")<9||a("ie")&&a("quirks")?function(a,b){var e=b*100,f=b==1;a.style.zoom=f?"":1;if(m(a))m(a,1).Opacity=e;else{if(f)return b;a.style.filter+=" progid:DXImageTransform.Microsoft.Alpha(Opacity="+e+")"}m(a,1).Enabled=!f;if(a.tagName.toLowerCase()=="tr")for(e=a.firstChild;e;e=e.nextSibling)e.tagName.toLowerCase()=="td"&&n(e,b);return b}:function(a,b){return a.style.opacity=
b},b={left:!0,top:!0},f=/margin|padding|width|height|max|min|offset/,l=a("ie")?"styleFloat":"cssFloat",q={cssFloat:l,styleFloat:l,"float":l};h.get=function(a,b){var e=i.byId(a),f=arguments.length;if(f==2&&b=="opacity")return g(e);var b=q[b]||b,d=h.getComputedStyle(e);return f==1?d:k(e,b,d[b]||e.style[b])};h.set=function(a,b,e){var f=i.byId(a),d=arguments.length,l=b=="opacity",b=q[b]||b;if(d==3)return l?n(f,e):f.style[b]=e;for(var g in b)h.set(a,g,b[g]);return h.getComputedStyle(f)};return h})},"dojo/dom-geometry":function(){define(["./_base/sniff",
"./_base/window","./dom","./dom-style"],function(a,i,k,o){function h(a,f,d,g,h,c){c=c||"px";a=a.style;if(!isNaN(f))a.left=f+c;if(!isNaN(d))a.top=d+c;if(g>=0)a.width=g+c;if(h>=0)a.height=h+c}function d(a){return a.tagName.toLowerCase()=="button"||a.tagName.toLowerCase()=="input"&&(a.getAttribute("type")||"").toLowerCase()=="button"}function m(a){return g.boxModel=="border-box"||a.tagName.toLowerCase()=="table"||d(a)}var g={boxModel:"content-box"};if(a("ie"))g.boxModel=document.compatMode=="BackCompat"?
"border-box":"content-box";g.getPadExtents=function(a,f){var a=k.byId(a),d=f||o.getComputedStyle(a),g=o.toPixelValue,h=g(a,d.paddingLeft),c=g(a,d.paddingTop),e=g(a,d.paddingRight),d=g(a,d.paddingBottom);return{l:h,t:c,r:e,b:d,w:h+e,h:c+d}};g.getBorderExtents=function(a,f){var a=k.byId(a),d=o.toPixelValue,g=f||o.getComputedStyle(a),h=g.borderLeftStyle!="none"?d(a,g.borderLeftWidth):0,c=g.borderTopStyle!="none"?d(a,g.borderTopWidth):0,e=g.borderRightStyle!="none"?d(a,g.borderRightWidth):0,d=g.borderBottomStyle!=
"none"?d(a,g.borderBottomWidth):0;return{l:h,t:c,r:e,b:d,w:h+e,h:c+d}};g.getPadBorderExtents=function(a,f){var a=k.byId(a),d=f||o.getComputedStyle(a),h=g.getPadExtents(a,d),d=g.getBorderExtents(a,d);return{l:h.l+d.l,t:h.t+d.t,r:h.r+d.r,b:h.b+d.b,w:h.w+d.w,h:h.h+d.h}};g.getMarginExtents=function(b,f){var b=k.byId(b),d=f||o.getComputedStyle(b),g=o.toPixelValue,h=g(b,d.marginLeft),c=g(b,d.marginTop),e=g(b,d.marginRight),g=g(b,d.marginBottom);a("webkit")&&d.position!="absolute"&&(e=h);return{l:h,t:c,
r:e,b:g,w:h+e,h:c+g}};g.getMarginBox=function(b,f){var b=k.byId(b),d=f||o.getComputedStyle(b),h=g.getMarginExtents(b,d),i=b.offsetLeft-h.l,c=b.offsetTop-h.t,e=b.parentNode,j=o.toPixelValue;if(a("mozilla")){var p=parseFloat(d.left),d=parseFloat(d.top);!isNaN(p)&&!isNaN(d)?(i=p,c=d):e&&e.style&&(e=o.getComputedStyle(e),e.overflow!="visible"&&(i+=e.borderLeftStyle!="none"?j(b,e.borderLeftWidth):0,c+=e.borderTopStyle!="none"?j(b,e.borderTopWidth):0))}else if((a("opera")||a("ie")==8&&!a("quirks"))&&e)e=
o.getComputedStyle(e),i-=e.borderLeftStyle!="none"?j(b,e.borderLeftWidth):0,c-=e.borderTopStyle!="none"?j(b,e.borderTopWidth):0;return{l:i,t:c,w:b.offsetWidth+h.w,h:b.offsetHeight+h.h}};g.getContentBox=function(b,f){var b=k.byId(b),d=f||o.getComputedStyle(b),h=b.clientWidth,i=g.getPadExtents(b,d),c=g.getBorderExtents(b,d);h?(d=b.clientHeight,c.w=c.h=0):(h=b.offsetWidth,d=b.offsetHeight);a("opera")&&(i.l+=c.l,i.t+=c.t);return{l:i.l,t:i.t,w:h-i.w-c.w,h:d-i.h-c.h}};g.setContentSize=function(a,f,d){var a=
k.byId(a),i=f.w,f=f.h;m(a)&&(d=g.getPadBorderExtents(a,d),i>=0&&(i+=d.w),f>=0&&(f+=d.h));h(a,NaN,NaN,i,f)};var n={l:0,t:0,w:0,h:0};g.setMarginBox=function(b,f,l){var b=k.byId(b),i=l||o.getComputedStyle(b),l=f.w,r=f.h,c=m(b)?n:g.getPadBorderExtents(b,i),i=g.getMarginExtents(b,i);if(a("webkit")&&d(b)){var e=b.style;if(l>=0&&!e.width)e.width="4px";if(r>=0&&!e.height)e.height="4px"}l>=0&&(l=Math.max(l-c.w-i.w,0));r>=0&&(r=Math.max(r-c.h-i.h,0));h(b,f.l,f.t,l,r)};g.isBodyLtr=function(){return(i.body().dir||
i.doc.documentElement.dir||"ltr").toLowerCase()=="ltr"};g.docScroll=function(){var b=i.doc.parentWindow||i.doc.defaultView;return"pageXOffset"in b?{x:b.pageXOffset,y:b.pageYOffset}:(b=a("quirks")?i.body():i.doc.documentElement,{x:g.fixIeBiDiScrollLeft(b.scrollLeft||0),y:b.scrollTop||0})};g.getIeDocumentElementOffset=function(){var b=i.doc.documentElement;if(a("ie")<8){var d=b.getBoundingClientRect(),g=d.left,d=d.top;a("ie")<7&&(g+=b.clientLeft,d+=b.clientTop);return{x:g<0?0:g,y:d<0?0:d}}else return{x:0,
y:0}};g.fixIeBiDiScrollLeft=function(b){var d=a("ie");if(d&&!g.isBodyLtr()){var h=a("quirks"),n=h?i.body():i.doc.documentElement;d==6&&!h&&i.global.frameElement&&n.scrollHeight>n.clientHeight&&(b+=n.clientLeft);return d<8||h?b+n.clientWidth-n.scrollWidth:-b}return b};g.position=function(b,d){var b=k.byId(b),h=i.body(),n=h.parentNode,m=b.getBoundingClientRect(),m={x:m.left,y:m.top,w:m.right-m.left,h:m.bottom-m.top};if(a("ie"))n=g.getIeDocumentElementOffset(),m.x-=n.x+(a("quirks")?h.clientLeft+h.offsetLeft:
0),m.y-=n.y+(a("quirks")?h.clientTop+h.offsetTop:0);else if(a("ff")==3){var h=o.getComputedStyle(n),c=o.toPixelValue;m.x-=c(n,h.marginLeft)+c(n,h.borderLeftWidth);m.y-=c(n,h.marginTop)+c(n,h.borderTopWidth)}d&&(n=g.docScroll(),m.x+=n.x,m.y+=n.y);return m};g.getMarginSize=function(a,d){var a=k.byId(a),h=g.getMarginExtents(a,d||o.getComputedStyle(a)),i=a.getBoundingClientRect();return{w:i.right-i.left+h.w,h:i.bottom-i.top+h.h}};g.normalizeEvent=function(b){if(!("layerX"in b))b.layerX=b.offsetX,b.layerY=
b.offsetY;if(!a("dom-addeventlistener")){var d=b.target,d=d&&d.ownerDocument||document,d=a("quirks")?d.body:d.documentElement,h=g.getIeDocumentElementOffset();b.pageX=b.clientX+g.fixIeBiDiScrollLeft(d.scrollLeft||0)-h.x;b.pageY=b.clientY+(d.scrollTop||0)-h.y}};return g})},"dojo/dom-prop":function(){define("dojo/dom-prop",["exports","./_base/kernel","./_base/sniff","./_base/lang","./dom","./dom-style","./dom-construct","./_base/connect"],function(a,i,k,o,h,d,m,g){var n={},b=0,f=i._scopeName+"attrid",
l={col:1,colgroup:1,table:1,tbody:1,tfoot:1,thead:1,tr:1,title:1};a.names={"class":"className","for":"htmlFor",tabindex:"tabIndex",readonly:"readOnly",colspan:"colSpan",frameborder:"frameBorder",rowspan:"rowSpan",valuetype:"valueType"};a.get=function(b,d){var b=h.byId(b),c=d.toLowerCase();return b[a.names[c]||d]};a.set=function(i,r,c){i=h.byId(i);if(arguments.length==2&&typeof r!="string"){for(var e in r)a.set(i,e,r[e]);return i}e=r.toLowerCase();e=a.names[e]||r;if(e=="style"&&typeof c!="string")return d.style(i,
c),i;if(e=="innerHTML")return k("ie")&&i.tagName.toLowerCase()in l?(m.empty(i),i.appendChild(m.toDom(c,i.ownerDocument))):i[e]=c,i;if(o.isFunction(c)){var j=i[f];j||(j=b++,i[f]=j);n[j]||(n[j]={});var p=n[j][e];if(p)g.disconnect(p);else try{delete i[e]}catch(t){}c?n[j][e]=g.connect(i,e,c):i[e]=null;return i}i[e]=c;return i}})},"dojo/dom-attr":function(){define(["exports","./_base/sniff","./_base/lang","./dom","./dom-style","./dom-prop"],function(a,i,k,o,h,d){function m(a,d){var g=a.getAttributeNode&&
a.getAttributeNode(d);return g&&g.specified}var g={innerHTML:1,className:1,htmlFor:i("ie"),value:1},n={classname:"class",htmlfor:"for",tabindex:"tabIndex",readonly:"readOnly"};a.has=function(a,f){var h=f.toLowerCase();return g[d.names[h]||f]||m(o.byId(a),n[h]||f)};a.get=function(a,f){var a=o.byId(a),h=f.toLowerCase(),i=d.names[h]||f,r=g[i];value=a[i];if(r&&typeof value!="undefined")return value;if(i!="href"&&(typeof value=="boolean"||k.isFunction(value)))return value;h=n[h]||f;return m(a,h)?a.getAttribute(h):
null};a.set=function(b,f,i){b=o.byId(b);if(arguments.length==2){for(var m in f)a.set(b,m,f[m]);return b}m=f.toLowerCase();var r=d.names[m]||f,c=g[r];if(r=="style"&&typeof i!="string")return h.set(b,i),b;if(c||typeof i=="boolean"||k.isFunction(i))return d.set(b,f,i);b.setAttribute(n[m]||f,i);return b};a.remove=function(a,d){o.byId(a).removeAttribute(n[d.toLowerCase()]||d)};a.getNodeProp=function(a,f){var a=o.byId(a),g=f.toLowerCase(),h=d.names[g]||f;if(h in a&&h!="href")return a[h];g=n[g]||f;return m(a,
g)?a.getAttribute(g):null}})},"dojo/dom-construct":function(){define("dojo/dom-construct",["exports","./_base/kernel","./_base/sniff","./_base/window","./dom","./dom-attr","./on"],function(a,i,k,o,h,d,m){function g(a,b){var c=b.parentNode;c&&c.insertBefore(a,b)}var n={option:["select"],tbody:["table"],thead:["table"],tfoot:["table"],tr:["table","tbody"],td:["table","tbody","tr"],th:["table","thead","tr"],legend:["fieldset"],caption:["table"],colgroup:["table"],col:["table","colgroup"],li:["ul"]},
b=/<\s*([\w\:]+)/,f={},l=0,q="__"+i._scopeName+"ToDomId",r;for(r in n)if(n.hasOwnProperty(r))i=n[r],i.pre=r=="option"?'<select multiple="multiple">':"<"+i.join("><")+">",i.post="</"+i.reverse().join("></")+">";var c=null,e;m(window,"unload",function(){c=null});a.toDom=function(a,c){var c=c||o.doc,e=c[q];e||(c[q]=e=++l+"",f[e]=c.createElement("div"));a+="";var d=a.match(b),g=d?d[1].toLowerCase():"",e=f[e];if(d&&n[g]){d=n[g];e.innerHTML=d.pre+a+d.post;for(d=d.length;d;--d)e=e.firstChild}else e.innerHTML=
a;if(e.childNodes.length==1)return e.removeChild(e.firstChild);for(g=c.createDocumentFragment();d=e.firstChild;)g.appendChild(d);return g};a.place=function(b,c,e){c=h.byId(c);typeof b=="string"&&(b=/^\s*</.test(b)?a.toDom(b,c.ownerDocument):h.byId(b));if(typeof e=="number"){var d=c.childNodes;!d.length||d.length<=e?c.appendChild(b):g(b,d[e<0?0:e])}else switch(e){case "before":g(b,c);break;case "after":e=b;(d=c.parentNode)&&(d.lastChild==c?d.appendChild(e):d.insertBefore(e,c.nextSibling));break;case "replace":c.parentNode.replaceChild(b,
c);break;case "only":a.empty(c);c.appendChild(b);break;case "first":if(c.firstChild){g(b,c.firstChild);break}default:c.appendChild(b)}return b};a.create=function(b,c,e,f){var g=o.doc;if(e)e=h.byId(e),g=e.ownerDocument;typeof b=="string"&&(b=g.createElement(b));c&&d.set(b,c);e&&a.place(b,e,f);return b};a.empty=k("ie")?function(b){for(var b=h.byId(b),c;c=b.lastChild;)a.destroy(c)}:function(a){h.byId(a).innerHTML=""};a.destroy=function(a){a=h.byId(a);try{var b=a.ownerDocument;if(!c||e!=b)c=b.createElement("div"),
e=b;c.appendChild(a.parentNode?a.parentNode.removeChild(a):a);c.innerHTML=""}catch(d){}}})},"dojo/keys":function(){define("dojo/keys",["./_base/kernel","./_base/sniff"],function(a,i){return a.keys={BACKSPACE:8,TAB:9,CLEAR:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,META:i("safari")?91:224,PAUSE:19,CAPS_LOCK:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT_ARROW:37,UP_ARROW:38,RIGHT_ARROW:39,DOWN_ARROW:40,INSERT:45,DELETE:46,HELP:47,LEFT_WINDOW:91,RIGHT_WINDOW:92,SELECT:93,NUMPAD_0:96,NUMPAD_1:97,
NUMPAD_2:98,NUMPAD_3:99,NUMPAD_4:100,NUMPAD_5:101,NUMPAD_6:102,NUMPAD_7:103,NUMPAD_8:104,NUMPAD_9:105,NUMPAD_MULTIPLY:106,NUMPAD_PLUS:107,NUMPAD_ENTER:108,NUMPAD_MINUS:109,NUMPAD_PERIOD:110,NUMPAD_DIVIDE:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,F13:124,F14:125,F15:126,NUM_LOCK:144,SCROLL_LOCK:145,UP_DPAD:175,DOWN_DPAD:176,LEFT_DPAD:177,RIGHT_DPAD:178,copyKey:i("mac")&&!i("air")?i("safari")?91:224:17}})},"dojo/domReady":function(){define(["./has"],
function(a){function i(a){m?a(1):g.push(a)}var k=this,o=document,h={loaded:1,complete:1},d=typeof o.readyState!="string",m=!!h[o.readyState];if(d)o.readyState="loading";if(!m){var g=[],n=[],b=function(a){a=a||k.event;if(!(m||a.type=="readystatechange"&&!h[o.readyState])){m=1;if(d)o.readyState="complete";for(;g.length;)g.shift()()}},f=function(a,e){a.addEventListener(e,b,!1);g.push(function(){a.removeEventListener(e,b,!1)})};if(!a("dom-addeventlistener")){var f=function(a,e){e="on"+e;a.attachEvent(e,
b);g.push(function(){a.detachEvent(e,b)})},l=o.createElement("div");try{l.doScroll&&k.frameElement===null&&n.push(function(){try{return l.doScroll("left"),1}catch(a){}})}catch(q){}}f(o,"DOMContentLoaded");f(k,"load");"onreadystatechange"in o?f(o,"readystatechange"):d||n.push(function(){return h[o.readyState]});if(n.length){var r=function(){if(!m){for(var a=n.length;a--;)if(n[a]()){b("poller");return}setTimeout(r,30)}};r()}}i.load=function(a,b,d){i(d)};return i})},"dojo/_base/lang":function(){define(["./kernel",
"../has","./sniff"],function(a,i){i.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var k=i("bug-for-in-skips-shadowed")?"hasOwnProperty.valueOf.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.constructor".split("."):[],o=k.length,h=function(a){a||(a={});for(var b=1,d=arguments.length;b<d;b++)r._mixin(a,arguments[b]);return a},d=function(b,e,d){var f,g=0,h=a.global;if(!d)if(b.length){f=b[g++];try{d=a.scopeMap[f]&&a.scopeMap[f][1]}catch(i){}d=d||(f in
h?h[f]:e?h[f]={}:void 0)}else return h;for(;d&&(f=b[g++]);)d=f in d?d[f]:e?d[f]={}:void 0;return d},m=function(a,b,f){return d(a.split("."),b,f)},g=Object.prototype.toString,n=function(){function a(){}return function(b,d){a.prototype=b;var f=new a;a.prototype=null;d&&r._mixin(f,d);return f}}(),b=function(a,b,d){return(d||[]).concat(Array.prototype.slice.call(a,b||0))},f=i("ie")?function(){function a(b,c,d){d=d||[];for(c=c||0;c<b.length;c++)d.push(b[c]);return d}return function(e){return(e.item?a:
b).apply(this,arguments)}}():b,l=function(a){if(!a||typeof a!="object"||r.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var b,d,f;if(r.isArray(a)){b=[];d=0;for(f=a.length;d<f;++d)d in a&&b.push(l(a[d]))}else b=a.constructor?new a.constructor:{};return r._mixin(b,a,l)},q=/\{([^\}]+)\}/g,r={_extraNames:k,_mixin:function(a,b,d){var f,g,h,l={};for(f in b)if(g=b[f],!(f in a)||a[f]!==
g&&(!(f in l)||l[f]!==g))a[f]=d?d(g):g;if(i("bug-for-in-skips-shadowed")&&b)for(h=0;h<o;++h)if(f=k[h],g=b[f],!(f in a)||a[f]!==g&&(!(f in l)||l[f]!==g))a[f]=d?d(g):g;return a},mixin:h,setObject:function(a,b,f){var g=a.split("."),a=g.pop();return(f=d(g,!0,f))&&a?f[a]=b:void 0},getObject:m,exists:function(a,b){return r.getObject(a,!1,b)!==void 0},isString:function(a){return typeof a=="string"||a instanceof String},isArray:function(a){return a&&(a instanceof Array||typeof a=="array")},isFunction:function(a){return g.call(a)===
"[object Function]"},isObject:function(a){return a!==void 0&&(a===null||typeof a=="object"||r.isArray(a)||r.isFunction(a))},isArrayLike:function(a){return a&&a!==void 0&&!r.isString(a)&&!r.isFunction(a)&&!(a.tagName&&a.tagName.toLowerCase()=="form")&&(r.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!r.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a){for(var b=1,d=arguments.length;b<d;b++)r._mixin(a.prototype,arguments[b]);return a},_hitchArgs:function(b,
e){var d=f(arguments,2),g=r.isString(e);return function(){var h=f(arguments),i=g?(b||a.global)[e]:e;return i&&i.apply(b||this,d.concat(h))}},hitch:function(b,e){if(arguments.length>2)return r._hitchArgs.apply(a,arguments);e||(e=b,b=null);if(r.isString(e)){b=b||a.global;if(!b[e])throw['dojo.hitch: scope["',e,'"] is null (scope="',b,'")'].join("");return function(){return b[e].apply(b,arguments||[])}}return!b?e:function(){return e.apply(b,arguments||[])}},delegate:n,_toArray:f,partial:function(){return r.hitch.apply(a,
[null].concat(r._toArray(arguments)))},clone:l,trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,b,d){return a.replace(d||q,r.isFunction(b)?b:function(a,c){return m(c,!1,b)})}};h(a,r);return r})},"dojo/Evented":function(){define(["./aspect","./on"],function(a,i){function k(){}var o=a.after;k.prototype={on:function(a,d){return i.parse(this,a,d,function(a,g){return o(a,"on"+g,d,!0)})},emit:function(){var a=[this];
a.push.apply(a,arguments);return i.emit.apply(i,a)}};return k})},"dojo/mouse":function(){define(["./_base/kernel","./on","./has","./dom","./_base/window"],function(a,i,k,o,h){function d(a,g){var h=function(b,d){return i(b,a,function(a){if(!o.isDescendant(a.relatedTarget,g?a.target:b))return d.call(this,a)})};if(!g)h.bubble=d(a,!0);return h}k.add("dom-quirks",h.doc&&h.doc.compatMode=="BackCompat");k.add("events-mouseenter",h.doc&&"onmouseenter"in h.doc.createElement("div"));k=k("dom-quirks")||!k("dom-addeventlistener")?
{LEFT:1,MIDDLE:4,RIGHT:2,isButton:function(a,d){return a.button&d},isLeft:function(a){return a.button&1},isMiddle:function(a){return a.button&4},isRight:function(a){return a.button&2}}:{LEFT:0,MIDDLE:1,RIGHT:2,isButton:function(a,d){return a.button==d},isLeft:function(a){return a.button==0},isMiddle:function(a){return a.button==1},isRight:function(a){return a.button==2}};a.mouseButtons=k;return{enter:d("mouseover"),leave:d("mouseout"),isLeft:k.isLeft,isMiddle:k.isMiddle,isRight:k.isRight}})},"dojo/topic":function(){define(["./Evented"],
function(a){var i=new a;return{publish:function(){return i.emit.apply(i,arguments)},subscribe:function(){return i.on.apply(i,arguments)}}})},"dojo/_base/xhr":function(){define(["./kernel","./sniff","require","../io-query","../dom","../dom-form","./Deferred","./json","./lang","./array","../on"],function(a,i,k,o,h,d,m,g,n,b,f){i.add("native-xhr",function(){return typeof XMLHttpRequest!=="undefined"});a._xhrObj=k.getXhr;var l=a.config;a.objectToQuery=o.objectToQuery;a.queryToObject=o.queryToObject;a.fieldToObject=
d.fieldToObject;a.formToObject=d.toObject;a.formToQuery=d.toQuery;a.formToJson=d.toJson;a._blockAsync=!1;var q=a._contentHandlers=a.contentHandlers={text:function(a){return a.responseText},json:function(a){return g.fromJson(a.responseText||null)},"json-comment-filtered":function(b){a.config.useCommentedJson||console.warn("Consider using the standard mimetype:application/json. json-commenting can introduce security issues. To decrease the chances of hijacking, use the standard the 'json' handler and prefix your json with: {}&&\nUse djConfig.useCommentedJson=true to turn off this message.");
var b=b.responseText,c=b.indexOf("/*"),e=b.lastIndexOf("*/");if(c==-1||e==-1)throw Error("JSON was not comment filtered");return g.fromJson(b.substring(c+2,e))},javascript:function(b){return a.eval(b.responseText)},xml:function(a){var c=a.responseXML;if(i("ie")&&(!c||!c.documentElement)){var e=function(a){return"MSXML"+a+".DOMDocument"},e=["Microsoft.XMLDOM",e(6),e(4),e(3),e(2)];b.some(e,function(b){try{var e=new ActiveXObject(b);e.async=!1;e.loadXML(a.responseText);c=e}catch(d){return!1}return!0})}return c},
"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?q["json-comment-filtered"](a):q.json(a)}};a._ioSetArgs=function(b,c,e,f){var g={args:b,url:b.url},i=null;if(b.form){var i=h.byId(b.form),j=i.getAttributeNode("action");g.url=g.url||(j?j.value:null);i=d.toObject(i)}j=[{}];i&&j.push(i);b.content&&j.push(b.content);b.preventCache&&j.push({"dojo.preventCache":(new Date).valueOf()});g.query=o.objectToQuery(n.mixin.apply(null,j));g.handleAs=b.handleAs||"text";
var k=new m(c);k.addCallbacks(e,function(a){return f(a,k)});var s=b.load;s&&n.isFunction(s)&&k.addCallback(function(a){return s.call(b,a,g)});var q=b.error;q&&n.isFunction(q)&&k.addErrback(function(a){return q.call(b,a,g)});var p=b.handle;p&&n.isFunction(p)&&k.addBoth(function(a){return p.call(b,a,g)});l.ioPublish&&a.publish&&g.args.ioPublish!==!1&&(k.addCallbacks(function(b){a.publish("/dojo/io/load",[k,b]);return b},function(b){a.publish("/dojo/io/error",[k,b]);return b}),k.addBoth(function(b){a.publish("/dojo/io/done",
[k,b]);return b}));k.ioArgs=g;return k};var r=function(a){a.canceled=!0;var b=a.ioArgs.xhr,c=typeof b.abort;(c=="function"||c=="object"||c=="unknown")&&b.abort();a=a.ioArgs.error;if(!a)a=Error("xhr cancelled"),a.dojoType="cancel";return a},c=function(a){a=q[a.ioArgs.handleAs](a.ioArgs.xhr);return a===void 0?null:a},e=function(a,b){b.ioArgs.args.failOk||console.error(a);return a},j=null,p=[],t=0,u=function(b){t<=0&&(t=0,l.ioPublish&&a.publish&&(!b||b&&b.ioArgs.args.ioPublish!==!1)&&a.publish("/dojo/io/stop"))},
s=function(){var b=(new Date).getTime();if(!a._blockAsync)for(var c=0,e;c<p.length&&(e=p[c]);c++){var d=e.dfd;(function(){if(!d||d.canceled||!e.validCheck(d))p.splice(c--,1),t-=1;else if(e.ioCheck(d))p.splice(c--,1),e.resHandle(d),t-=1;else if(d.startTime&&d.startTime+(d.ioArgs.args.timeout||0)<b){p.splice(c--,1);var a=Error("timeout exceeded");a.dojoType="timeout";d.errback(a);d.cancel();t-=1}}).call(this)}u(d);p.length||(clearInterval(j),j=null)};a._ioCancelAll=function(){try{b.forEach(p,function(a){try{a.dfd.cancel()}catch(b){}})}catch(a){}};
i("ie")&&f(window,"unload",a._ioCancelAll);a._ioNotifyStart=function(b){l.ioPublish&&a.publish&&b.ioArgs.args.ioPublish!==!1&&(t||a.publish("/dojo/io/start"),t+=1,a.publish("/dojo/io/send",[b]))};a._ioWatch=function(a,b,c,e){var d=a.ioArgs.args;if(d.timeout)a.startTime=(new Date).getTime();p.push({dfd:a,validCheck:b,ioCheck:c,resHandle:e});j||(j=setInterval(s,50));d.sync&&s()};var B=function(a){return a.ioArgs.xhr.readyState},w=function(a){return 4==a.ioArgs.xhr.readyState},C=function(b){var c=b.ioArgs.xhr;
if(a._isDocumentOk(c))b.callback(b);else{var e=Error("Unable to load "+b.ioArgs.url+" status:"+c.status);e.status=c.status;e.responseText=c.responseText;e.xhr=c;b.errback(e)}};a._ioAddQueryToUrl=function(a){if(a.query.length)a.url+=(a.url.indexOf("?")==-1?"?":"&")+a.query,a.query=null};a.xhr=function(b,d,f){var g=a._ioSetArgs(d,r,c,e),h=g.ioArgs,i=h.xhr=a._xhrObj(h.args);if(!i)return g.cancel(),g;"postData"in d?h.query=d.postData:"putData"in d?h.query=d.putData:"rawBody"in d?h.query=d.rawBody:(arguments.length>
2&&!f||"POST|PUT".indexOf(b.toUpperCase())==-1)&&a._ioAddQueryToUrl(h);i.open(b,h.url,d.sync!==!0,d.user||void 0,d.password||void 0);if(d.headers)for(var j in d.headers)j.toLowerCase()==="content-type"&&!d.contentType?d.contentType=d.headers[j]:d.headers[j]&&i.setRequestHeader(j,d.headers[j]);d.contentType!==!1&&i.setRequestHeader("Content-Type",d.contentType||"application/x-www-form-urlencoded");(!d.headers||!("X-Requested-With"in d.headers))&&i.setRequestHeader("X-Requested-With","XMLHttpRequest");
a._ioNotifyStart(g);if(a.config.debugAtAllCosts)i.send(h.query);else try{i.send(h.query)}catch(l){h.error=l,g.cancel()}a._ioWatch(g,B,w,C);return g};a.xhrGet=function(b){return a.xhr("GET",b)};a.rawXhrPost=a.xhrPost=function(b){return a.xhr("POST",b,!0)};a.rawXhrPut=a.xhrPut=function(b){return a.xhr("PUT",b,!0)};a.xhrDelete=function(b){return a.xhr("DELETE",b)};a._isDocumentOk=function(a){a=a.status||0;return a>=200&&a<300||a==304||a==1223||!a};a._getText=function(b){var c;a.xhrGet({url:b,sync:!0,
load:function(a){c=a}});return c};n.mixin(a.xhr,{_xhrObj:a._xhrObj,fieldToObject:d.fieldToObject,formToObject:d.toObject,objectToQuery:o.objectToQuery,formToQuery:d.toQuery,formToJson:d.toJson,queryToObject:o.queryToObject,contentHandlers:q,_ioSetArgs:a._ioSetArgs,_ioCancelAll:a._ioCancelAll,_ioNotifyStart:a._ioNotifyStart,_ioWatch:a._ioWatch,_ioAddQueryToUrl:a._ioAddQueryToUrl,_isDocumentOk:a._isDocumentOk,_getText:a._getText,get:a.xhrGet,post:a.xhrPost,put:a.xhrPut,del:a.xhrDelete});return a.xhr})},
"dojo/_base/unload":function(){define(["./kernel","./connect"],function(a,i){var k=window;a.addOnWindowUnload=function(o,h){if(!a.windowUnloaded)i.connect(k,"unload",a.windowUnloaded=function(){});i.connect(k,"unload",o,h)};a.addOnUnload=function(a,h){i.connect(k,"beforeunload",a,h)};return{addOnWindowUnload:a.addOnWindowUnload,addOnUnload:a.addOnUnload}})},"dojo/_base/NodeList":function(){define(["./kernel","../query","./array","./html","../NodeList-dom"],function(a,i,k){var i=i.NodeList,o=i.prototype;
o.connect=i._adaptAsForEach(function(){return a.connect.apply(this,arguments)});o.coords=i._adaptAsMap(a.coords);i.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];k.forEach(i.events,function(a){var d="on"+a;o[d]=function(a,g){return this.connect(d,a,g)}});a.NodeList=i;return a.NodeList})},"dojo/_base/Color":function(){define(["./kernel","./lang","./array","./config"],function(a,
i,k,o){var h=a.Color=function(a){a&&this.setColor(a)};h.named={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255],transparent:o.transparentColor||[0,0,0,0]};i.extend(h,{r:255,g:255,b:255,a:1,_set:function(a,h,g,i){this.r=a;this.g=h;this.b=g;this.a=i},setColor:function(a){i.isString(a)?
h.fromString(a,this):i.isArray(a)?h.fromArray(a,this):(this._set(a.r,a.g,a.b,a.a),a instanceof h||this.sanitize());return this},sanitize:function(){return this},toRgb:function(){return[this.r,this.g,this.b]},toRgba:function(){return[this.r,this.g,this.b,this.a]},toHex:function(){return"#"+k.map(["r","g","b"],function(a){a=this[a].toString(16);return a.length<2?"0"+a:a},this).join("")},toCss:function(a){var h=this.r+", "+this.g+", "+this.b;return(a?"rgba("+h+", "+this.a:"rgb("+h)+")"},toString:function(){return this.toCss(!0)}});
h.blendColors=a.blendColors=function(a,i,g,n){var b=n||new h;k.forEach(["r","g","b","a"],function(f){b[f]=a[f]+(i[f]-a[f])*g;f!="a"&&(b[f]=Math.round(b[f]))});return b.sanitize()};h.fromRgb=a.colorFromRgb=function(a,i){var g=a.toLowerCase().match(/^rgba?\(([\s\.,0-9]+)\)/);return g&&h.fromArray(g[1].split(/\s*,\s*/),i)};h.fromHex=a.colorFromHex=function(a,i){var g=i||new h,n=a.length==4?4:8,b=(1<<n)-1,a=Number("0x"+a.substr(1));if(isNaN(a))return null;k.forEach(["b","g","r"],function(f){var h=a&b;
a>>=n;g[f]=n==4?17*h:h});g.a=1;return g};h.fromArray=a.colorFromArray=function(a,i){var g=i||new h;g._set(Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]));if(isNaN(g.a))g.a=1;return g.sanitize()};h.fromString=a.colorFromString=function(a,i){var g=h.named[a];return g&&h.fromArray(g,i)||h.fromRgb(a,i)||h.fromHex(a,i)};return h})},"dojo/selector/_loader":function(){define(["../has","require"],function(a,i){var k=document.createElement("div");a.add("dom-qsa2.1",!!k.querySelectorAll);a.add("dom-qsa3",
function(){try{return k.innerHTML="<p class='TEST'></p>",k.querySelectorAll(".TEST:empty").length==1}catch(a){}});var o;return{load:function(h,d,k){var g=i,h=h=="default"?a("config-selectorEngine")||"css3":h,h=h=="css2"||h=="lite"?"./lite":h=="css2.1"?a("dom-qsa2.1")?"./lite":"./acme":h=="css3"?a("dom-qsa3")?"./lite":"./acme":h=="acme"?"./acme":(g=d)&&h;if(h.charAt(h.length-1)=="?")var h=h.substring(0,h.length-1),n=!0;if(n&&(a("dom-compliant-qsa")||o))return k(o);g([h],function(a){h!="./lite"&&(o=
a);k(a)})}}})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(a,i,k){function o(a,b,e,d,f){if(d=b.match(/(.*):(.*)/))return b=d[2],d=d[1],g.selector(d,b).call(f,a,e);k("touch")&&(n.test(b)&&(e=u(e)),!k("event-orientationchange")&&b=="orientationchange"&&(b="resize",a=window,e=u(e)));if(a.addEventListener){var h=b in l;a.addEventListener(h?l[b]:b,e,h);return{remove:function(){a.removeEventListener(b,e,h)}}}b="on"+b;if(c&&a.attachEvent)return c(a,
b,e);throw Error("Target must be an event emitter");}function h(){this.cancelable=!1}function d(){this.bubbles=!1}var m=window.ScriptEngineMajorVersion;k.add("jscript",m&&m()+ScriptEngineMinorVersion()/10);k.add("event-orientationchange",k("touch")&&!k("android"));var g=function(a,b,c,e){if(a.on)return a.on(b,c);return g.parse(a,b,c,o,e,this)};g.pausable=function(a,b,c,e){var d,a=g(a,b,function(){if(!d)return c.apply(this,arguments)},e);a.pause=function(){d=!0};a.resume=function(){d=!1};return a};
g.once=function(a,b,c){var e=g(a,b,function(){e.remove();return c.apply(this,arguments)});return e};g.parse=function(a,b,c,e,d,f){if(b.call)return b.call(f,a,c);if(b.indexOf(",")>-1){for(var b=b.split(/\s*,\s*/),g=[],h=0,i;i=b[h++];)g.push(e(a,i,c,d,f));g.remove=function(){for(var a=0;a<g.length;a++)g[a].remove()};return g}return e(a,b,c,d,f)};var n=/^touch/;g.selector=function(a,b,c){return function(e,d){var f=this,h=b.bubble;h?b=h:c!==!1&&(c=!0);return g(e,b,function(b){var g=b.target;for(f=f&&
f.matches?f:i.query;!f.matches(g,a,e);)if(g==e||!c||!(g=g.parentNode))return;return d.call(g,b)})}};var b=[].slice,f=g.emit=function(a,c,e){var f=b.call(arguments,2),g="on"+c;if("parentNode"in a){var i=f[0]={},j;for(j in e)i[j]=e[j];i.preventDefault=h;i.stopPropagation=d;i.target=a;i.type=c;e=i}do a[g]&&a[g].apply(a,f);while(e&&e.bubbles&&(a=a.parentNode));return e&&e.cancelable&&e},l={};if(k("dom-addeventlistener")){l={focusin:"focus",focusout:"blur"};if(k("opera"))l.keydown="keypress";g.emit=function(a,
b,c){if(a.dispatchEvent&&document.createEvent){var e=document.createEvent("HTMLEvents");e.initEvent(b,!!c.bubbles,!!c.cancelable);for(var d in c)d in e||(e[d]=c[d]);return a.dispatchEvent(e)&&e}return f.apply(g,arguments)}}else{g._fixEvent=function(a,b){if(!a)a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event;if(!a)return a;if(!a.target){a.target=a.srcElement;a.currentTarget=b||a.srcElement;if(a.type=="mouseover")a.relatedTarget=a.fromElement;if(a.type=="mouseout")a.relatedTarget=
a.toElement;if(!a.stopPropagation)a.stopPropagation=e,a.preventDefault=j;switch(a.type){case "keypress":var c="charCode"in a?a.charCode:a.keyCode;c==10?(c=0,a.keyCode=13):c==13||c==27?c=0:c==3&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}}return a};var q=function(a){this.handle=a};q.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var r=function(a){return function(b){b=g._fixEvent(b,this);return a.call(this,b)}},
c=function(b,c,e){e=r(e);if(((b.ownerDocument?b.ownerDocument.parentWindow:b.parentWindow||b.window||window)!=top||k("jscript")<5.8)&&!k("config-_allow_leaks")){typeof _dojoIEListeners_=="undefined"&&(_dojoIEListeners_=[]);var d=b[c];if(!d||!d.listeners){var f=d;b[c]=d=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];d.global=this;f&&d.listeners.push(_dojoIEListeners_.push(f)-
1)}d.listeners.push(b=d.global._dojoIEListeners_.push(e)-1);return new q(b)}return a.after(b,c,e,!0)},e=function(){this.cancelBubble=!0},j=g._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.returnValue=!1}}if(k("touch"))var p=function(){},t=window.orientation,u=function(a){return function(b){var c=b.corrected;if(!c){var e=b.type;try{delete b.type}catch(d){}b.type?(p.prototype=b,c=new p,c.preventDefault=function(){b.preventDefault()},c.stopPropagation=
function(){b.stopPropagation()}):(c=b,c.type=e);b.corrected=c;if(e=="resize"){if(t==window.orientation)return null;t=window.orientation;c.type="orientationchange";return a.call(this,c)}if(!("rotation"in c))c.rotation=0,c.scale=1;var e=c.changedTouches[0],f;for(f in e)delete c[f],c[f]=e[f]}return a.call(this,c)}};return g})},"dojo/_base/sniff":function(){define(["./kernel","../has"],function(a,i){a.isBrowser=!0;a._name="browser";var k=i.add,o=navigator,h=o.userAgent,d=o.appVersion,m=parseFloat(d),
g,n,b,f,l,q,r,c,e,j,p,t,u;h.indexOf("AdobeAIR")>=0&&(n=1);b=d.indexOf("Konqueror")>=0?m:0;f=parseFloat(h.split("WebKit/")[1])||void 0;l=parseFloat(h.split("Chrome/")[1])||void 0;q=d.indexOf("Macintosh")>=0;t=/iPhone|iPod|iPad/.test(h);u=parseFloat(h.split("Android ")[1])||void 0;var s=Math.max(d.indexOf("WebKit"),d.indexOf("Safari"),0);if(s&&!l&&(r=parseFloat(d.split("Version/")[1]),!r||parseFloat(d.substr(s+7))<=419.3))r=2;if(!i("dojo-webkit")&&(h.indexOf("Opera")>=0&&(g=m,g>=9.8&&(g=parseFloat(h.split("Version/")[1])||
m)),h.indexOf("Gecko")>=0&&!b&&!f&&(c=e=m),e&&(p=parseFloat(h.split("Firefox/")[1]||h.split("Minefield/")[1])||void 0),document.all&&!g))j=parseFloat(d.split("MSIE ")[1])||void 0,(h=document.documentMode)&&h!=5&&Math.floor(j)!=h&&(j=h);h=document.compatMode=="BackCompat";k("opera",a.isOpera=g);k("air",a.isAIR=n);k("khtml",a.isKhtml=b);k("webkit",a.isWebKit=f);k("chrome",a.isChrome=l);k("mac",a.isMac=q);k("safari",a.isSafari=r);k("mozilla",a.isMozilla=a.isMoz=c);k("ie",a.isIE=j);k("ff",a.isFF=p);k("quirks",
a.isQuirks=h);k("ios",a.isIos=t);k("android",a.isAndroid=u);a.locale=a.locale||(j?o.userLanguage:o.language).toLowerCase();return i})},"dojo/_base/array":function(){define("dojo/_base/array",["./kernel","../has","./lang"],function(a,i,k){function o(a){return m[a]=new Function("item","index","array",a)}function h(a){var d=!a;return function(g,h,i){var c=0,e=g&&g.length||0,j;e&&typeof g=="string"&&(g=g.split(""));typeof h=="string"&&(h=m[h]||o(h));if(i)for(;c<e;++c){if(j=!h.call(i,g[c],c,g),a^j)return!j}else for(;c<
e;++c)if(j=!h(g[c],c,g),a^j)return!j;return d}}function d(a){var d=1,h=0,i=0;a||(d=h=i=-1);return function(k,c,e,j){if(j&&d>0)return n.lastIndexOf(k,c,e);var j=k&&k.length||0,m=a?j+i:h;e===g?e=a?h:j+i:e<0?(e=j+e,e<0&&(e=h)):e=e>=j?j+i:e;for(j&&typeof k=="string"&&(k=k.split(""));e!=m;e+=d)if(k[e]==c)return e;return-1}}var m={},g,n;n={every:h(!1),some:h(!0),indexOf:d(!0),lastIndexOf:d(!1),forEach:function(a,d,g){var h=0,i=a&&a.length||0;i&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=
m[d]||o(d));if(g)for(;h<i;++h)d.call(g,a[h],h,a);else for(;h<i;++h)d(a[h],h,a)},map:function(a,d,g,h){var i=0,c=a&&a.length||0,h=new (h||Array)(c);c&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=m[d]||o(d));if(g)for(;i<c;++i)h[i]=d.call(g,a[i],i,a);else for(;i<c;++i)h[i]=d(a[i],i,a);return h},filter:function(a,d,g){var h=0,i=a&&a.length||0,c=[],e;i&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=m[d]||o(d));if(g)for(;h<i;++h)e=a[h],d.call(g,e,h,a)&&c.push(e);else for(;h<
i;++h)e=a[h],d(e,h,a)&&c.push(e);return c},clearCache:function(){m={}}};k.mixin(a,n);return n})},"dojo/_base/json":function(){define(["./kernel","../json"],function(a,i){a.fromJson=function(a){return eval("("+a+")")};a._escapeString=i.stringify;a.toJsonIndentStr="\t";a.toJson=function(k,o){return i.stringify(k,function(a,d){if(d){var i=d.__json__||d.json;if(typeof i=="function")return i.call(d)}return d},o&&a.toJsonIndentStr)};return a})},"dojo/dom-class":function(){define(["./_base/lang","./_base/array",
"./dom"],function(a,i,k){function o(a){if(typeof a=="string"||a instanceof String){if(a&&!d.test(a))return m[0]=a,m;a=a.split(d);a.length&&!a[0]&&a.shift();a.length&&!a[a.length-1]&&a.pop();return a}if(!a)return[];return i.filter(a,function(a){return a})}var h,d=/\s+/,m=[""],g={};return h={contains:function(a,b){return(" "+k.byId(a).className+" ").indexOf(" "+b+" ")>=0},add:function(a,b){var a=k.byId(a),b=o(b),d=a.className,g,d=d?" "+d+" ":" ";g=d.length;for(var h=0,i=b.length,c;h<i;++h)(c=b[h])&&
d.indexOf(" "+c+" ")<0&&(d+=c+" ");g<d.length&&(a.className=d.substr(1,d.length-2))},remove:function(d,b){var d=k.byId(d),f;if(b!==void 0){b=o(b);f=" "+d.className+" ";for(var g=0,h=b.length;g<h;++g)f=f.replace(" "+b[g]+" "," ");f=a.trim(f)}else f="";d.className!=f&&(d.className=f)},replace:function(a,b,d){a=k.byId(a);g.className=a.className;h.remove(g,d);h.add(g,b);a.className!==g.className&&(a.className=g.className)},toggle:function(a,b,d){a=k.byId(a);if(d===void 0)for(var b=o(b),g=0,i=b.length,
m;g<i;++g)m=b[g],h[h.contains(a,m)?"remove":"add"](a,m);else h[d?"add":"remove"](a,b);return d}}})},"dojo/_base/window":function(){define(["./kernel","../has","./sniff"],function(a,i){a.doc=this.document||null;a.body=function(){return a.doc.body||a.doc.getElementsByTagName("body")[0]};a.setContext=function(i,h){a.global=k.global=i;a.doc=k.doc=h};a.withGlobal=function(i,h,d,m){var g=a.global;try{return a.global=k.global=i,a.withDoc.call(null,i.document,h,d,m)}finally{a.global=k.global=g}};a.withDoc=
function(o,h,d,m){var g=a.doc,n=a.isQuirks,b=a.isIE,f,l,q;try{a.doc=k.doc=o;a.isQuirks=i.add("quirks",a.doc.compatMode=="BackCompat",!0,!0);if(i("ie")&&(q=o.parentWindow)&&q.navigator)f=parseFloat(q.navigator.appVersion.split("MSIE ")[1])||void 0,(l=o.documentMode)&&l!=5&&Math.floor(f)!=l&&(f=l),a.isIE=i.add("ie",f,!0,!0);d&&typeof h=="string"&&(h=d[h]);return h.apply(d,m||[])}finally{a.doc=k.doc=g,a.isQuirks=i.add("quirks",n,!0,!0),a.isIE=i.add("ie",b,!0,!0)}};var k={global:a.global,doc:a.doc,body:a.body,
setContext:a.setContext,withGlobal:a.withGlobal,withDoc:a.withDoc};return k})},"dojo/_base/config":function(){define(["../has","require"],function(a,i){var k={},o=i.rawConfig,h;for(h in o)k[h]=o[h];return k})},"dojo/_base/event":function(){define(["./kernel","../on","../has","../dom-geometry"],function(a,i,k,o){if(i._fixEvent){var h=i._fixEvent;i._fixEvent=function(a,i){(a=h(a,i))&&o.normalizeEvent(a);return a}}a.fixEvent=function(a,h){if(i._fixEvent)return i._fixEvent(a,h);return a};a.stopEvent=
function(a){k("dom-addeventlistener")||a&&a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a=a||window.event,a.cancelBubble=!0,i._preventDefault.call(a))};return{fix:a.fixEvent,stop:a.stopEvent}})},"dojo/main":function(){define(["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(a,
i,k,o,h,d,m){a.config.isDebug&&k(["./_firebug/firebug"]);var g=a.config.require;g&&(g=d.map(h.isArray(g)?g:[g],function(a){return a.replace(/\./g,"/")}),a.isAsync?k(g):m(1,function(){k(g)}));return a})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(a,i,k,o,h){var d=0,m,g=[],n=0,b=function(){if(d&&!n&&g.length){n=1;var a=g.shift();try{a()}finally{n=0}n=0;g.length&&m(b)}};k.on("idle",b);m=function(){k.idle()&&b()};var i=a.ready=a.addOnLoad=
function(b,d,f){var c=h._toArray(arguments);typeof b!="number"?(f=d,d=b,b=1E3):c.shift();f=f?h.hitch.apply(a,c):function(){d()};f.priority=b;for(c=0;c<g.length&&b>=g[c].priority;c++);g.splice(c,0,f);m()},f=a.config.addOnLoad;if(f)i[h.isArray(f)?"apply":"call"](a,f);a.config.parseOnLoad&&!a.isAsync&&i(99,function(){a.parser||(a.deprecated("Add explicit require(['dojo/parser']);","","2.0"),k(["dojo/parser"]))});o(function(){d=1;a._postLoad=a.config.afterOnLoad=!0;g.length&&m(b)});return i})},"dojo/aspect":function(){define([],
function(){function a(a,i,h,d){var m=a[i],g=i=="around",n;if(g){var b=h(function(){return m.advice(this,arguments)});n={remove:function(){n.cancelled=!0},advice:function(a,d){return n.cancelled?m.advice(a,d):b.apply(a,d)}}}else n={remove:function(){var b=n.previous,d=n.next;if(!d&&!b)delete a[i];else if(b?b.next=d:a[i]=d,d)d.previous=b},advice:h,receiveArguments:d};if(m&&!g)if(i=="after"){for(h=m;h;)m=h,h=h.next;m.next=n;n.previous=m}else{if(i=="before")a[i]=n,n.next=m,m.previous=n}else a[i]=n;return n}
function i(i){return function(o,h,d,m){var g=o[h],n;if(!g||g.target!=o){n=o[h]=function(){for(var a=arguments,d=n.before;d;)a=d.advice.apply(this,a)||a,d=d.next;if(n.around)var g=n.around.advice(this,a);for(d=n.after;d;)g=d.receiveArguments?d.advice.apply(this,a)||g:d.advice.call(this,g),d=d.next;return g};if(g)n.around={advice:function(a,d){return g.apply(a,d)}};n.target=o}o=a(n||g,i,d,m);d=null;return o}}return{before:i("before"),around:i("around"),after:i("after")}})},"dojo/_base/connect":function(){define(["./kernel",
"../on","../topic","../aspect","./event","../mouse","./sniff","./lang","../keys"],function(a,i,k,o,h,d,m,g){function n(b,c,f,h,k){h=g.hitch(f,h);if(!b||!b.addEventListener&&!b.attachEvent)return o.after(b||a.global,c,h,!0);typeof c=="string"&&c.substring(0,2)=="on"&&(c=c.substring(2));if(!b)b=a.global;if(!k)switch(c){case "keypress":c=r;break;case "mouseenter":c=d.enter;break;case "mouseleave":c=d.leave}return i(b,c,h,k)}function b(a){a.keyChar=a.charCode?String.fromCharCode(a.charCode):"";a.charOrCode=
a.keyChar||a.keyCode}m.add("events-keypress-typed",function(){var a={charCode:0};try{a=document.createEvent("KeyboardEvent"),(a.initKeyboardEvent||a.initKeyEvent).call(a,"keypress",!0,!0,null,!1,!1,!1,!1,9,3)}catch(b){}return a.charCode==0&&!m("opera")});var f={106:42,111:47,186:59,187:43,188:44,189:45,190:46,191:47,192:96,219:91,220:92,221:93,222:39,229:113},l=m("mac")?"metaKey":"ctrlKey",q=function(a,c){var d=g.mixin({},a,c);b(d);d.preventDefault=function(){a.preventDefault()};d.stopPropagation=
function(){a.stopPropagation()};return d},r;r=m("events-keypress-typed")?function(a,b){var c=i(a,"keydown",function(a){var c=a.keyCode,d=(c!=13||m("ie")>=9&&!m("quirks"))&&c!=32&&(c!=27||!m("ie"))&&(c<48||c>90)&&(c<96||c>111)&&(c<186||c>192)&&(c<219||c>222)&&c!=229;if(d||a.ctrlKey){d=d?0:c;if(a.ctrlKey)if(c==3||c==13)return b.call(a.currentTarget,a);else d>95&&d<106?d-=48:!a.shiftKey&&d>=65&&d<=90?d+=32:d=f[d]||d;c=q(a,{type:"keypress",faux:!0,charCode:d});b.call(a.currentTarget,c);if(m("ie"))try{a.keyCode=
c.keyCode}catch(e){}}}),d=i(a,"keypress",function(a){var c=a.charCode,a=q(a,{charCode:c>=32?c:0,faux:!0});return b.call(this,a)});return{remove:function(){c.remove();d.remove()}}}:m("opera")?function(a,b){return i(a,"keypress",function(a){var c=a.which;c==3&&(c=99);c=c<32&&!a.shiftKey?0:c;a.ctrlKey&&!a.shiftKey&&c>=65&&c<=90&&(c+=32);return b.call(this,q(a,{charCode:c}))})}:function(a,c){return i(a,"keypress",function(a){b(a);return c.call(this,a)})};var c={_keypress:r,connect:function(){var a=arguments,
b=[],c=0;b.push(typeof a[0]=="string"?null:a[c++],a[c++]);var d=a[c+1];b.push(typeof d=="string"||typeof d=="function"?a[c++]:null,a[c++]);for(d=a.length;c<d;c++)b.push(a[c]);return n.apply(this,b)},disconnect:function(a){a&&a.remove()},subscribe:function(a,b,c){return k.subscribe(a,g.hitch(b,c))},publish:function(a,b){return k.publish.apply(k,[a].concat(b))},connectPublisher:function(a,b,d){var f=function(){c.publish(a,arguments)};return d?c.connect(b,d,f):c.connect(b,f)},isCopyKey:function(a){return a[l]}};
c.unsubscribe=c.disconnect;g.mixin(a,c);return c})}}});(function(){var a=this.require;a({cache:{}});!a.async&&a(["dojo"]);a.boot&&a.apply(null,a.boot)})();