<form  action="<?php echo $this->escape($this->element->getAction())?>" method="<?php echo $this->escape($this->element->getMethod())?>">
<table style="width:100%" class="params">
	<tr>
		<td style="width: 250px"><?php echo $this->element->period->getLabel() ?></td>
		<td><?php echo $this->element->period ?></td>
		<td rowspan="4">&nbsp;</td>
		<td class="btn" rowspan="3"><?php echo $this->element->refresh ?><br/><?php echo $this->element->excel ?></td>
	</tr>
	<tr>
		<td><?php echo $this->element->reportfpocategory->getLabel() ?></td>
		<td><?php echo $this->element->reportfpocategory ?></td>
	</tr>
	<tr>
		<td><?php echo $this->element->edubase->getLabel() ?></td>
		<td><?php echo $this->element->edubase ?></td>
	</tr>
	<tr>
		<td><?php echo $this->element->countrytype->getLabel() ?></td>
		<td><?php echo $this->element->countrytype ?></td>
	</tr>
</table>
</form>