<a name="top" ></a>
<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td height="106" width="190"><img src="/modules/contingent/img/top_le.jpg" width="190" height="106" /></td>
		<td height="106" width="100%" style="background-image: url('/modules/contingent/img/top_bg.gif')"><img src="/modules/contingent/img/top_ce.gif" width="626" height="106" /></td>
		<td height="106" width="206" align="right"><img src="/modules/contingent/img/top_ri.gif" width="206" height="106" /></td>
	</tr>
	<tr style="height: 100%">
		<td valign="top" style="background-image: url('/modules/contingent/img/bg_menu.gif')">
			<img src="/modules/contingent/img/le.jpg" width="190" height="134" align="top" />
			<?php echo $this->render('page/menu.phtml')?>
		</td>
		<td colspan="2" valign="top" style="background-image: url('/modules/contingent/img/ri.jpg'); background-repeat: repeat-y; background-position: right; margin-right: 30px">
			<?php echo $this->action($this->node_info['CONTENT_GEN'], 'typecontent', 'contingent')?>
		</td>
	</tr>
	<tr>
		<td width="190" style="height: 19px; background-image: url('/modules/contingent/img/niz_le.jpg')">&nbsp;</td>
		<td colspan="2" style="background-image: url('/modules/contingent/img/niz_ri.gif'); background-position: right; background-repeat: no-repeat">&nbsp;</td>
	</tr>
	<tr>
		<td width="190" bgcolor="#f6f9fd">&#160;</td>
		<td colspan="2" bgcolor="#f6f9fd" style="background-repeat: repeat-y; background-position: right;">&#160;</td>
	</tr>
</table>