<table width="100%" height="100%">
	<tr>
		<td class="sep1">
			<div>&nbsp;</div>
		</td>
	</tr>
	<tr height="25px">
		<td>
				<h2 class="artitle">
		      <?php echo $this->translate ( "skin.hint.map" )?>
		    </h2>
		</td>
	</tr>
	<tr>
		<td class="cnt">
		<div>
			<ul>
<?php
foreach($this->map as $item)
	echo "<li style=\"margin-left:" . $item['NODE_LEVEL'] * 25 . "px\"><a href=\"{$item['HREF']}\" target=\"{$item['DOC_TARGET']}\">{$item['TITLE']}</a></li>";
?>
			</ul>
		</div>
		</td>
	</tr>
	<tr>
		<td class="sep2"><div /></td>
	</tr>
</table>