<table class="menu" cellpadding="0" cellspacing="0">
<?php foreach ($this->link_items as $val): ?>
<tr style="height: 31px; background-image: url(/modules/site/img/menu.jpg);">
	<td style="vertical-align: middle;">
		<a href="<?php echo $val['HREF']?>" target="_self"><?php echo $val['TITLE']?></a>
	</td>
</tr>
<?php endforeach?>
<?php if($this->authInfoHelper()->TITLE != 'guest'):?>
	<tr style="height: 100px;">
		<td style="vertical-align: bottom;">
		<table cellpadding="0" cellspacing="0"
			style="margin-left: 20px; width: 200px; height: 100%">
			<tr>
				<td>
					<div style="height: 20px;">&#160;</div>
				</td>
			</tr>
			<tr>
				<td class="sep1">
					<div></div>
				</td>
			</tr>
			<tr>
				<td style="padding: 2px"><span class="blu main2"><?php
				echo $this->translate ( "skin.user" )?></span>
				</td>
			</tr>
			<tr>
				<td class="cnt">
					<div style="text-align: center" class="blu">
						<?php	echo $this->authInfoHelper()->TITLE?>
					</div>
				</td>
			</tr>
			<tr>
				<td class="sep2">
					<div style="height: 2px;"></div>
				</td>
			</tr>
		</table>
		</td>
	</tr>
<?php endif?>
<?php foreach ($this->menu_items as $val): ?>
<tr style="height: 31px; background-image: url(/modules/contingent/img/menu.jpg);">
	<td style="vertical-align: middle;">
		<a href="<?php echo $val['HREF']?>" target="_self"><?php echo $val['TITLE']?></a>
	</td>
</tr>
<?php endforeach?>
</table>