<a name="top" ></a>
<table height="240" width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td height="240" width="190"><img src="/modules/site/img/le.jpg" width="190" height="240" /></td>
		<td height="240" width="100%">
			<table height="240" width="100%" cellpadding="0" cellspacing="0">
				<tr>
			  		<td height="170" class="center">
		  				<br> 					
						<?php	echo $this->translate("skin.orgname_full")?>
						<br>
					</td>
				</tr>			
				<tr style="height: 50px;">
					<td valign="bottom">
						<p>&nbsp;</p>						
						[<a href="/auth" class="key" title="<?php echo $this->translate ( "skin.hint.login" )?>">
							Авторизация
						</a>]&nbsp;&nbsp;
						[<a href="mailto:contingent@tdmu.edu.ua" class="mail" title="<?php	echo $this->translate ( "skin.hint.mail" )?>">
							Написать письмо
						</a>]&nbsp;&nbsp;
						<?php
							$langs_count = count($this->menu_languages);
							foreach ($this->menu_languages as $key => $val) {
								if ($key <= 2) {
									echo "[<a href=\"{$this->url(array('docid' => $val ['NODEID'], 'controller' => 'page'), null, true)}\" class=\"{$val ['LOCALE_CODE']}\" title=\"{$val ['TITLE']}\">{$val ['TITLE']}</a>]&nbsp;&nbsp;";
								}
							}
						?>
						<?php if ($langs_count > 3) :?>
							<a id="langs_icon" href="#" onclick="showmenu()" class="lang"	title="Other languages">&#160;</a>
						<?php endif?>
					</td>
				</tr>
			</table>
		</td>
		<td height="240" width="206" align="right"><br><br><img src="/modules/site/img/top_ri.gif" width="206" height="106" /></td>
	</tr>
	<tr style="height: 100%">
		<td valign="top">			
			<?php echo $this->render('page/menu.phtml')?>
		</td>
		<td colspan="2" valign="top" style="background-image: url('/modules/site/img/ri.jpg'); background-repeat: repeat-y; background-position: right; margin-right: 30px">
			<?php echo $this->action($this->node_info['CONTENT_GEN'], 'typecontent', 'site')?>
		</td>
	</tr>
	<tr>
		<td width="190" style="height: 19px; ">&nbsp;</td>
		<td colspan="2">&nbsp;</td>
	</tr>
	<tr>
		<td width="190" bgcolor="#f6f9fd">&#160;</td>
		<td colspan="2" bgcolor="#f6f9fd" style="background-repeat: repeat-y; background-position: right;">&#160;</td>
	</tr>
</table>