
<h2 style="text-align: center;">Цей формат пакетів застарілий та не підтримується.</h2>
<!-- 
<form id="<?php echo $this->element->getName ()?>" action="<?php echo $this->element->getAction ()?>" method="<?php echo $this->element->getMethod ()?>" enctype="<?php echo $this->element->getEnctype ()?>">
<?php echo $this->element->step?>
<?php echo $this->element->filename?>
<h2 style="text-align: center;">Інформація про пакет:</h2>
<hr>
<table align="center">
	<tr>
		<td style="width: 100px">Назва організіції</td>
		<td><?php echo $this->info['OrgName']?></td>
	</tr>
	<tr>
		<td>Період з</td>
		<td><?php echo $this->info['D1']?></td>
	</tr>
	<tr>
		<td>по</td>
		<td><?php echo $this->info['D2']?></td>
	</tr>
	<tr>
		<td>Дата створення</td>
		<td><?php echo $this->info['CreateDate']?></td>
	</tr>
	<tr>
		<td>Тип пакету</td>
		<td><?php echo $this->info['PackageType']?></td>
	</tr>
	<tr>
		<td>Версія пакету</td>
		<td><?php echo $this->info['Version']?></td>
	</tr>
	<tr>
		<td colspan="2"><div  align="center"><br/><br/><?php echo $this->element->submit?></div></td>
	</tr>
</table>
</form>
 -->