<form action="<?php echo $this->element->getAction ()?>" method="<?php echo $this->element->getMethod ()?>" enctype="<?php echo $this->element->getEnctype ()?>">
<?php echo $this->element->step?>
<h2 style="text-align: center;">Виберіть файл пакету:</h2>
<div style="text-align: center;"><?php echo $this->element->file?></div>
<br>
<div style="text-align: center;"><?php echo $this->element->submit?></div>

</form>