<?php $this->headStyle()->captureStart();?>
.zend_form {  
	background:#fff;  
	width: 800px;  
	margin: 20px;  
}  

.zend_form tr {  
	padding: 0;  
	margin: 5px 2px 5px 0;  
}  

.zend_form .errors {
	color: red;
}

.zend_form input, .zend_form textarea{  
	margin: 0 0 2px 0;  
	padding: 0;  
}  

.required {
	font-weight: bold;
}

.required:before {
	content: '* ';
}

.cnt .message {
	color: red; 
	font-size: 14px; 
	margin-top: 20px; 
	margin-left: 30px;
}  
<?php $this->headStyle()->captureEnd();?>
<?php $this->headScript()->captureStart() ?>
function checkReply(form) {
  return form.replyto.value || confirm("<?php echo $this->translate('You didn\'t enter your e-mail address. If you\'ve sent a question, we are not able to answer it. Continue?')?>");
}
<?php $this->headScript()->captureEnd() ?>
<table width="100%" height="100%">
	<tr>
		<td class="sep1">
		<div>$nbsp;</div>
		</td>
	</tr>
	<tr height="25px">
		<td>
		<div class="main"><?php	echo $this->node_info['TITLE']?></div>
		</td>
	</tr>
	<tr>
		<td class="cnt">
<?php if($this->form) :?>
<?php echo $this->content?><br />
<?php echo $this->form?>
<?php endif?>
<?php if($this->message) :?>
<span class="message"><?php echo $this->translate($this->message)?></span>
<?php endif?>		</td>
	</tr>
	<tr>
		<td class="sep2">
		<div>$nbsp;</div>
		</td>
	</tr>
</table>