<?php
	if ($this->form) {
		echo '<div style="text-align:center;font-size:20px;font-weight:bold;">' . $this->title . '</div><hr/>';
		echo $this->form->render();
		echo '<div id="formError"></div>';

		if(isset($this->javascript)) {
			echo '<div id="dialogScript" style="display:none">&nbsp;<script type="text/javascript">';
			echo "function execFormScript() {\n";
			echo "var baseUrl = '{$this->baseUrl}';\n";
			echo "var baseHref = 'http://{$_SERVER['HTTP_HOST']}/tmp/{$this->id}/';\n";
			echo "var id = '{$this->id}';\n";
			echo $this->javascript;
			echo "}";
			echo '</script></div>';
		}	
	}
?>