<table cellpadding="0" cellspacing="0" width="100%">
	<!-- [TOP] -->
	<tr>
		<td id="top">
		<table cellpadding="0" cellspacing="0" width="100%" height="100%"
			class="head">
			<tr>
				<td class="for" />


				<td style="width: 130px; text-align: center; vertical-align: middle"
					rowspan="2"><img src="/modules/stat/img/glob.gif" /></td>
			</tr>
			<tr>
				<td>
				<table cellpadding="0" cellspacing="1" height="100%">
					<tr>
						<td style="width: 100px; text-align: center"><a href="/"><img
							src="/modules/stat/img/home.gif" /></a></td>

						<?php
							function renderMenu(&$menuItems, $level = 0) {
								foreach ( $menuItems as $val ) {
									$id = $val['NODEID'];
									$title = str_replace(' ', '&nbsp;', $val['TITLE']);
									if ($level == 0)
										echo "<td class=\"menu\"><a href=\"#\" onclick=\"showmenu(this, {$id}); return false;\"  onmouseover=\"setOver(true); showmenu(this, {$id}); return false;\" onmouseout=\"setOver(false)\">{$title}</a>";
									else {
										echo "<tr><td><a href=\"{$val['HREF']}\" target=\"{$val['DOC_TARGET']}\">{$title}</a></td></tr>";
									}

									if (isset ( $val ['childs'] )) {
										echo "<table cellspacing=\"0\" id=\"sm_{$id}\" class=\"submenu\" style=\"display:none\" onmouseover=\"setOver(true)\" onmouseout=\"setOver(false)\">";
										renderMenu ( $val ['childs'], $level + 1 );
										echo "</table>";
																										}
										if ($level == 0) echo "</td>";
									}
								}

								$menuItems = $this->dbModel->getMenuItems ( $this->node_info ['MENU_NODEID'], true );
								renderMenu ( $menuItems );
							?>

						</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<!-- [///TOP] -->

	<!-- [CENTER] -->
	<tr>
		<td height="100%" id="center">
			<?php echo $this->action($this->content_gen, 'typecontent', 'stat', $this->queryParams)
//			echo $this->render ( 'gen_'.$this->node_info['CONTENT_GEN'].'.phtml' );?>
		</td>
	</tr>
	<!-- [///CENTER] -->

	<!-- [BOTTOM] -->
	<tr>
		<td id="bot"></td>
	</tr>
</table>